### ISSUE TITLE
监听58"转转"APP时,currentActivity() 无法正确获取"我发布的"名称(低概率能正确获取)

### ISSUE THREAD

**Issue by asiontang** [hyb1996/Auto.js#202]
TYPE_WINDOW_STATE_CHANGED:
正确界面名称: com.wuba.zhuanzhuan.activity.MyIssuedActivity
却拿到的名称: com.wuba.zhuanzhuan.components.ZZLoadingDialog

初步调试发现,ZZLoadingDialog这个加载中的界面一瞬间就消失了,所以应该是 notificationTimeout="100" 事件的通知频率问题.

一瞬间太短了,notificationTimeout现在的时间不知道还能否再降低?不知道是否影响性能?

初步阅读源码后,还是没找到解决方案.

**Comment by hyb1996** [comment]
目测确实可能是[notificationTimeout](https://developer.android.com/reference/android/accessibilityservice/AccessibilityServiceInfo.html) 的锅。可以试试改小一点。我会测试改小以后是否明显影响性能并在下个版本中修改notificationTimeout。

**Comment by hyb1996** [comment]
notificationTimeout减小会明显降低性能，在低性能手机上有明显卡顿。因此保持为原来的100ms。

**Comment by asiontang** [comment]
现在使用的不完美方案是(供后来者参考): 主动打开"最近打开APP的列表"后, 再回到之前的界面.此时就能正常获取正确的界面名称了.
