### ISSUE TITLE
是否支持定时操作

### ISSUE THREAD

**Issue by cn-qlg** [hyb1996/Auto.js#224]
就像windows计划任务一样，每天几点开始执行，执行几次。
目前我的想法是，让脚本一直跑，然后判断时间，比如要求早上8点整开始，跑三次。那就建一个死循环，一直跑，等当前时间等于8:00的时候，开始执行各种操作。执行完之后，继续等。
看到大佬前几天更新了一个脚本引擎的说明，似乎可以实现这个任务，但是因为没有例子。我尝试直接写在脚本里面，但是不行，报错说未定义。

**Comment by hyb1996** [comment]
目前如果要比较好地支持定时的话，用Tasker吧。

**Comment by hyb1996** [comment]
在此次提交（https://github.com/hyb1996/Auto.js/commit/97382965da97bf118d99ac70bfba0df138d398f8）中已经支持了了该功能
