### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Winter-is-comming** [hyb1996/Auto.js#253]
作者将语法什么的，还有UI写进帮助文档吧，我想打印，谢谢 ，或者搞个word pdf什么的，或者你把文档补齐，我来做word。
还有就是建议：1、搞一个脚本调试的功能，就是在控制台显示当前运行的语句
2、建议文档中的事例不建议使用for(var=.......)什么的，就留下单个语句就行，估计小白根本看不懂
3：用了下录制脚本，感觉无论是运行or查看都很麻烦，太详细了。。。导致运行效率不高，可以只记录Tap() sleep() Swipe()就可以了
4：一些软件中有QQ登录，查了下登录按钮desc为"登 录"（注：登录中间有空格），于是试了下中括号中的代码，不知道对不对[desc("登 录").click();]麻烦指正，还有万恶的验证，请问怎么判断图中拼图的最左边纵坐标，并swipe拼图至对应位置。

**Comment by hyb1996** [comment]
1.文档正在完善。
2.调试功能的话太难做，等3.0发布后再考虑。
3.示例都会更新。
4.录制脚本比较难优化，等3.0发布再考虑。
5.代码是正确的

**Comment by Winter-is-comming** [comment]
收到，谢谢回复。
我所说的调试是指在每一句执行时在控制台显示该语句，举个栗子：
"auto";

console.show();
console.log("Tap(x,y)");
Tap(x,y);
console.log("Swipe(x1,y1,x2,y2,1000)");
Swipe(x1,y1,x2,y2,1000);
....
就是不需要在手动添加console.log()

**Comment by pboymt** [comment]
正好我想基于electron做编辑调试工具……

**Comment by hyb1996** [comment]
调试功能目前已经支持。
