### ISSUE TITLE
webview

### ISSUE THREAD

**Issue by zoulux** [hyb1996/Auto.js#254]
请问webview中的元素click没有任何反应

**Comment by Winter-is-comming** [comment]
我也是

**Comment by hyb1996** [comment]
webview的元素点击需支持无障碍的浏览器，例如chrome。

**Comment by Winter-is-comming** [comment]
一般都是在一些软件里需要点击，我换了一种办法如中括号中[do {tap(x,y)}] while(waitForActivity("com.xxx.xxx",500));       就是do-while语句，先点击x,y点直到Activity为com.xxx.xxx，没出现再循环
