### ISSUE TITLE
关于媒体键的控制的几个疑问

### ISSUE THREAD

**Issue by Ancientwood** [hyb1996/Auto.js#255]
+ 是否没有 KEYCODE_MEDIA_PLAY_PAUSE 
+ 是否能阻塞或重写例如: volume_down 时的音量 Toast 通知显示，当然这也就是想要*保持当前音量*
+ 关于「Stop all scripts when volume changes」选项，本机测试为当按下 音量+ 时停止所有脚本，是否能增加选项例如:连按两下音量+停止所有脚本 (毕竟实体按键少
+ 此外已发布的打包工具是否能够使用？
+ 最后，预祝老板生意兴隆，财源广进。(大雾，坏耶

**Comment by hyb1996** [comment]
* 根据实际测试，耳机键的播放键是`KEYCODE_HEADSETHOOK`
* 如果想自定义音量控制，可以写一个小模块(double_volume_down_to_exit.js)，比如:
```
module.exports = function(){
    threads.start(function(){
        events.observeKey();
        var lastVolumeUpTime = 0;
        events.onKeyDown("volume_up", function(){
            //连续两次音量上键小于500毫秒
            if(new Date().getTime() - lastVolumeUpTime < 500){
                //则退出脚本
                exit();
            }
            lastVolumeUpTime = new Date().getTime();
        });
    });
}
```
在其他脚本中引用该模块即可：
```
require("double_volume_down_to_exit.js")();
```
* 打包工具是可以使用的，需要配合最新内测版(Alpha36以上)使用

**Comment by Ancientwood** [comment]
十分感谢！
冒昧再次请教，按下 **音量+/-** 能否保持当前音量，或者不显示音量改变的通知？
2018，祝好。

**Comment by hyb1996** [comment]
目前的版本是不能做到的，主要考虑到恶意脚本可能借此屏蔽用户按键。
不过在未来的版本的会考虑加入该功能。

**Comment by xwj1612** [comment]
@hyb1996  询问下，按键事件是异步问题在3.0中还有吗，比如循环中无法监听按键事件

还有发现，外置存储卡文件可以exists检测到，但是无法重命名和复制到外置路径

而且函数getsdcardpath获取到的是内部sdcard

**Comment by hyb1996** [comment]
按键监听可以可以用[threads](https://hyb1996.github.io/AutoJs-Docs/threads.html)模块启用新线程来监听。只要在新线程执行events.observeKey()即可。
外置存储卡的问题我需要确认一下

**Comment by xwj1612** [comment]
@hyb1996  模块是不是要3.0了 我等下安装测试下。。

如果你用的是getExternalStorageDirectory()
获取的实际是内置SD卡路径...

印象好像没有外置路径的api

**Comment by xwj1612** [comment]
age = prompt("请输入年龄", "");
if (age != null) {
  alert(age)
}else{
   alert('取消了')}

3.0版本 取消输入框后，代码不继续往下执行了，进程中脚本还在执行中

**Comment by xwj1612** [comment]
@hyb1996   再反馈个问题，悬浮窗布局分析的时候，状态栏没有解析出来，导致解析出来窗格都上移一个状态栏高度，虽然也能用，但是用起来比较难受。  开发者模式里面那个显示布局边界是对的。

s8 安卓7.0  这可能是系统适配问题？

**Comment by hyb1996** [comment]
我分别确认和修复这些问题。另外建议一个问题发一个issue，比较好管理一点点
感谢反馈~

**Comment by xwj1612** [comment]
@hyb1996 双音量键那样控制不行哦。。  脑补完一测试果然会冲突。。

**Comment by Ancientwood** [comment]
> 怎么大风越吹，我心越荡

*各位有在妖风中凌乱嘛🙃*

*双音量键* 当然是要取消原先的 **「音量上键停止所有脚本」** 嘛 @xwj1612 

目前我最常用的就是下面这个，仅为了解决自己的需求，因为实体按键太少而妥协（。
 *音量+* 选择 *音量-* 的功能：
+ 组合剪贴板输出 Telegram 的 markdown link
+ scrolldown
+ pause script

```js
events.observeKey();
var choose = dialogs.singleChoice("Choose", ["Markdown", "Scroll","Pause"], 2);

  events.onKeyDown("volume_down", function(event) {
    if (choose == 0) {
      var input = rawInput('Text');
      var mdHead = '@bold [' + input + '](';
      var clip = getClip();
      var output = mdHead + clip + ')';
      setClip(output);
    }else if(choose == 1){
      scrollDown();
    }
  });
  events.onKeyDown("volume_up", function(event) {
     if (choose == 2) {
        
     }else{
      choose = dialogs.singleChoice("Choose", ["Markdown", "Scroll","Pause"], 2);
     }
    
  })
var lastVolumeUpTime = 0;
events.onKeyDown("volume_up", function() {
  //连续两次音量上键小于500毫秒
  if (new Date().getTime() - lastVolumeUpTime < 500) {
    choose = dialogs.singleChoice("Choose", ["Markdown", "Scroll","Pause"], 2);
  }
  lastVolumeUpTime = new Date().getTime();
});
```

*突发奇想:* 耳机线控上下**选取控件**，播放键**模拟点击**，线控上下双击 **scroll 滑屏**，播放键双击模拟**返回** *（这简直是冬日广大被窝党的福音*
所以还是强烈希望 按下 *音量+/-* 能够保持**当前音量**，或 不显示音量改变的**通知** @hyb1996
*私以为防止恶意脚本屏蔽用户按键与不显示音量改变的通知并不矛盾，即使也可以使用电源键嘛，不了解内部机制随口一说（*

**Comment by 2767321434** [comment]
按键这个，还是建议加入能屏蔽默认操作的功能，确实很需要这个。防止恶意程序这个，可以设置不屏蔽电源按键，同时在通知栏有退出功能，这样就能避免恶意脚本了。

**Comment by xwj1612** [comment]
@Ancientwood  不是取消上键停止那个啦，如果定义上键肯定要取消的，那个停止是系统级的。。

问题是如果同时定义下 和双击下  那么双击下的时候会执行两次下。。 比如我分别定义停止和恢复的功能，双击的时候就会冲突

**Comment by xwj1612** [comment]
@Ancientwood  按键双击这个问题可能无解。。 除非底层的集成，不然双击的时候必然要额外触发两次单击的定义功能

或者可以定义单击等待时间，超时1秒执行，1秒内双击，1秒内3击。。。脑补到了奇怪的思路。。

**Comment by Ancientwood** [comment]
@xwj1612 这个思路感觉ok的

**Comment by nmdx** [comment]
哈哈，经过1年的学习应用，现在终于会解这个了

```
//双击音量键的判断
threads.start(function() {
    events.observeKey();
    events.onKeyDown("volume_down", function() {
        t();
    });
});
var status = false;
var d1, d2;
function t() {
    if (!status) {
        status = true;
        d1 = (new Date().getTime());
    } else {
        d2 = (new Date().getTime());
        if (d2 - d1 < 500) {
            toast("时间小于500");
        } else {
            toast("时间大于500")
        }
        status = false;
    }
}
```
