### ISSUE TITLE
截图尺寸问题

### ISSUE THREAD

**Issue by lulee007** [hyb1996/Auto.js#258]
华为荣耀8(1080x1920)，带虚拟导航栏截图的尺寸是1088x1872? 没有加上导航栏的高度，
尝试在`ScreenMetrics.java`修改获取屏幕尺寸的获取方式:
```java
activity.getWindowManager().getDefaultDisplay().getMetrics(metrics);
deviceScreenHeight = metrics.heightPixels;
deviceScreenWidth = metrics.widthPixels;
```
为
```java
Point size = new Point();
activity.getWindowManager().getDefaultDisplay().getRealSize(size);
deviceScreenHeight = size.y;
deviceScreenWidth = size.x;
```
能够得到 1080x1920 ，但是截图后的尺寸为1088x1920,wtf??
********
**EDIT: 2018年01月03日10:41:12**
找到了多的8个像素，在`com.stardust.autojs.core.image:ImageWrapper:toBitmap`
```java
 int pixelStride = plane.getPixelStride();
 int rowPadding = plane.getRowStride() - pixelStride * image.getWidth();
 Bitmap bitmap = Bitmap.createBitmap(image.getWidth() + rowPadding / pixelStride, 
 image.getHeight(), Bitmap.Config.ARGB_8888);
```
为何要加 ` rowPadding / pixelStride`，如何能保持原有宽度？
  
********
**EDIT: 2018年01月03日11:16:24**
在`com.stardust.autojs.core.image:ImageWrapper:toBitmap`添加一句，
```java
...
 Bitmap bitmap = Bitmap.createBitmap(image.getWidth() + rowPadding / pixelStride, 
 image.getHeight(), Bitmap.Config.ARGB_8888);
// 再次裁剪一下即可
bitmap = Bitmap.createBitmap(bitmap, 0, 0, image.getWidth(), image.getHeight());
return bitmap
```

**Comment by hyb1996** [comment]
确实有这个问题，至于为什么加上rowPadding / pixelStride，很可能是我从STO上直接复制的代码。我需要确认一下rowPadding / pixelStride的必要性和再次createBitmap的性能损失。

**Comment by hyb1996** [comment]
确认了rowPadding / pixelStride的必要性，也没有找到其他的比直接剪切的更快的方法。这样性能损失大约为每次截图多消耗2~5ms的时间，还算勉强可以接受。
