### ISSUE TITLE
编辑器的问题

### ISSUE THREAD

**Issue by hyb1996** [hyb1996/Auto.js#262]
1. 光标乱跳: 具体变现为输入过程光标不跟随输入的字符。可能是以下代码导致的：
```javascript
editor.on("keyup", function(editor, event)
{
    if (!ExcludedIntelliSenseTriggerKeys[(event.keyCode || event.which).toString()] )
    {
        editor.execCommand("autocomplete");
    }
});
```

2. 输入的字符自动删掉: 具体变现为某些情况下，在一行的开始位置无法输入字符，只要输入一个字符就会自动删掉。原因可能和1相同。

3. 无法全选复制：点击全选后没有显示复制、剪切的菜单。可能需要重写InputConnection。

4. 没有对自定义函数和变量的自动补全: 看CodeMirror插件中是否有这个。没有的话用正则粗暴解决。

5. xml格式化代码问题: 格式化代码时会将xml格式弄乱。需要修改js beautifier。

6. 无法使用输入法进行选择、复制、粘贴: 点击输入法的选择、复制、粘贴等键时无反应。可能需要重写InputConnection。

**Comment by MikaGuraN** [comment]
在我一个4.4的手机上编辑器无法删除一行(最多删空，就是删不掉一个空行)，不知道怎么回事

**Comment by hyb1996** [comment]
7. 编辑器保存，运行有时会崩溃的问题

**Comment by hyb1996** [comment]
更换了编辑器。因此不再有这些问题。
