### ISSUE TITLE
源代码打包后出错

### ISSUE THREAD

**Issue by agreatwang** [hyb1996/Auto.js#264]
我配置好了环境运行你的源代码，在编译器上能够运行，用pyinstaller打包后就运行不了了，我想请问一下，你是用的什么库打包的？

**Comment by hyb1996** [comment]
pyinstaller打包？pyinstaller不是打包python脚本的吗

**Comment by agreatwang** [comment]
你是用什么打包的？

**Comment by agreatwang** [comment]
不好意思，刚才发现问错人了
