### ISSUE TITLE
等一个EditTextAttrSetter

### ISSUE THREAD

**Issue by MikaGuraN** [hyb1996/Auto.js#270]
动态XML布局无法设置EditText的一些属性...

**Comment by hyb1996** [comment]
根据Android文档, [EditText](https://developer.android.com/reference/android/widget/EditText.html)应该没有比TextView多出其他属性

**Comment by MikaGuraN** [comment]
@hyb1996  EditText指针的Drawable....

**Comment by hyb1996** [comment]
由于textCursorDrawable不能在代码中设置，因此直接当当做TextView处理吧
