### ISSUE TITLE
错误处理导致<手机按键失效>的问题

### ISSUE THREAD

**Issue by MikaGuraN** [hyb1996/Auto.js#271]
一开始我以为只是我的手机有这个问题，结果我换了手机Auto.js出错了还是有这个问题。。。
而且只有Auto.js出错了会导致按键失效。。
除了电源键，其他的按键按下去全都没用了！！

个人认为是Auto.js的按键监听的问题.....

**Comment by MikaGuraN** [comment]
不过电源键没有被屏蔽...

**Comment by hyb1996** [comment]
Auto.js崩溃的时候就会出现这种问题...这个暂时没有解决办法...
