### ISSUE TITLE
希望增加控件截图或指定区域截图、socket支持等

### ISSUE THREAD

**Issue by boedge** [hyb1996/Auto.js#275]
希望增加控件截图或指定区域截图、socket支持，不知道有没有这样的计划？
另外针对longclickAble=false，而实际可以长按弹出菜单的控件，press在真机上可用，但模拟器（5.1）上不知为何无效。
（官网不开放注册了吗？）

**Comment by hyb1996** [comment]
Socket可以直接使用java.net.Socket，区域截图实际上只能是截图后剪切，所以后续提供图片剪切的代码就好了。
模拟器不用press的话只能用root的Swipe代替。
官网暂时关闭注册，等考完试把短信验证加上后再开放

**Comment by boedge** [comment]
ok,多谢回复！有没有可以加的群呢？
（方便告诉你在哪个城市哪个学校吗）

**Comment by boedge** [comment]
还想再请教一下，有的控件内容是文字，但text，desc都是空的，但有需要获得文字内容，有什么方法吗，或者以后会不会有OCR的代码？

**Comment by hyb1996** [comment]
QQ群 586823180。
学校广州中山大学。
OCR的话目前只能调用在线API。

**Comment by Winter-is-comming** [comment]
作者是学医的？

**Comment by hyb1996** [comment]
....中山大学=学医...??→_→

**Comment by msnlcl** [comment]
作者是外科专家，，，针对的病人叫安卓！

**Comment by Winter-is-comming** [comment]
那为什么中山大学网站上全是什么医学院什么的
