### ISSUE TITLE
无障碍服务

### ISSUE THREAD

**Issue by palmer650** [hyb1996/Auto.js#283]
Autojs无障碍服务会给每个脚本都开启同样的服务，无论需不需要，这样会对用户的操作造成干扰，譬如:检索窗口内容服务。当不需要检索窗口内容的脚本运行的同时，使用其它应用有时候会在屏幕上出现黄色的搜索框，干扰正常使用，能否在Autojs和打包插件打包时可以指定需要开启的无障碍服务

**Comment by Ancientwood** [comment]
重启/清后台后 无障碍服务 需要重新开启，不知是否是我个例

**Comment by pboymt** [comment]
我这里还遇到了莫名其妙就开启监听音量键的服务，这个不出意外就是bug。

**Comment by pboymt** [comment]
@Ancientwood 你这个不是个例，我没记错的话如果后台被杀了，无障碍服务都会被关闭，所有应用都这样

**Comment by Ancientwood** [comment]
@pboymt 后台贮存，重启，有的应用不需要重新赋权限。

**Comment by hyb1996** [comment]
如果不使用"auto"或auto()的话脚本是不会请求无障碍服务器权限的。
至于音量键监听，设置里关闭就行了...

**Comment by palmer650** [comment]
@hyb1996 需要使用auto的脚本可不可以考虑无障碍服务权限请求的内容根据需要自己选择，不需要的可以不用申请，因为在有些设备上这些服务被申请后会造成干扰

**Comment by pboymt** [comment]
音量键监听我关闭了也有监听啊……

**Comment by hyb1996** [comment]
@pboymt 你指的是什么监听 音量键关闭所有脚本？

**Comment by pboymt** [comment]
@Ancientwood 我也很奇怪这个，不过还有一点，我这里一般都是auto.js闪退之后权限才没了的

**Comment by Ancientwood** [comment]
没有使用`auto`用了`keys`和`events`也需要无障碍权限 @hyb1996

**Comment by hyb1996** [comment]
@Ancientwood 本来那些命令就是依赖于无障碍服务的。参见文档说明。按键监听就是用无障碍服务实现的，当然需要开启无障碍。

**Comment by Ancientwood** [comment]
之前还特意打开文档看了看再问，结果真的写了，我瞎(ง •_•)ง

**Comment by pboymt** [comment]
@hyb1996 我的意思是我手机如果有应用监听音量键的话，调音量会出现很大的延迟，但是我把所有监听（脚本和Auto.js自己的）都关掉之后还有监听行为，这时候必须强退Auto.js在重启才能正常。

**Comment by hyb1996** [comment]
@pboymt 如果出现这种情况，直接关闭无障碍服务就好了。
但是我觉得这不应该是Auto.js的问题，因为Auto.js在处理按键事情时是在另一个线程处理的，绝不会影响事件的反馈和继续传递，因此我觉得可能是系统的问题。

**Comment by pboymt** [comment]
@hyb1996 这个问题我去问问Flyme攻城狮，顺便有好多文档的问题我QQ给你说了你没回……
