### ISSUE TITLE
循环运行没有如期执行

### ISSUE THREAD

**Issue by e1399579** [hyb1996/Auto.js#287]
步骤：选择一个脚本，点击循环运行，默认选项
结果：只运行了一次
期望：按选项一直运行
版本：3.0.0 alpha40

**Comment by hyb1996** [comment]
默认选项就是只运行一次吧

**Comment by hyb1996** [comment]
请给出无法循环运行的具体的代码

**Comment by e1399579** [comment]
[蚂蚁森林.zip](https://github.com/hyb1996/Auto.js/files/1688248/default.zip)

**Comment by hyb1996** [comment]
循环支持现已从项目中移除
