### ISSUE TITLE
Crash后再启动识图功能失效，除非重启手机

### ISSUE THREAD

**Issue by pboymt** [hyb1996/Auto.js#288]
在任何情况下都会出现这个问题，包括进程被系统加速器杀死后也会触发这个问题。

没有啥具体可以提供的信息，这是我开发的时候通过日志试出来的……可以识别的图片无法识别

**Comment by e1399579** [comment]
同样遇到这个问题，事实上，captureScreen()会返回null而没有抛出异常

**Comment by pboymt** [comment]
这个bug已经修复了，现在又出现了运行脚本偶现载图失败的bug，这个我另提issue吧
