### ISSUE TITLE
image下面能否增加一个将图片加入相册的方法

### ISSUE THREAD

**Issue by boedge** [hyb1996/Auto.js#294]
当然最好是图片、视频文件都可以加入相册，
如果没有这个方法，未root的是不是根本就没有办法实现呢，还是用java非root也可以做到？

**Comment by boedge** [comment]
广播？

**Comment by pboymt** [comment]
加入相册是啥意思啊……如果你要保存图片的话，不是有saveTo方法么？直接保存到Pictures目录即可

**Comment by hyb1996** [comment]
可以增加一个通知媒体库的方法

**Comment by boedge** [comment]
已经java实现，加个方法应该也是很简单的

**Comment by hyb1996** [comment]
已经在commit https://github.com/hyb1996/Auto.js/commit/4b4c823db552030dfe0753b562c5391b22240215中添加了media模块，使用`media.scanFile()`即可。
