### ISSUE TITLE
ReferenceError: "ScriptEngine" is not defined.

### ISSUE THREAD

**Issue by e1399579** [hyb1996/Auto.js#297]
步骤：代码片断
```
log(ScriptEngine);
```
结果：Log: 16:11:20.270/E: ReferenceError: "ScriptEngine" is not defined. (<<remote>:E:\autojs\蚂蚁森林>#24)
	at script(<<remote>:E:\autojs\蚂蚁森林>:24)
期望：加上这个API

**Comment by XeroAlpha** [comment]
本来就没有这个全局引用啊，这只是个对象类型
```
var current = engines.myEngine(); //获得引擎
console.log(current.cwd()); //记录当前目录
```
