### ISSUE TITLE
如何退出打开的应用？

### ISSUE THREAD

**Issue by pgkiller** [hyb1996/Auto.js#299]
我在脚本中按照操作手机方法back(); 
结果和实际按的结果不一样。
经测试recents()和back()的功能一样。是什么原因。
是由于手机没root吗

**Comment by hyb1996** [comment]
请给出手机型号、系统、安卓版本等信息

**Comment by pgkiller** [comment]
360N5S  Android 7.1.1  v023

**Comment by pgkiller** [comment]
🙃

**Comment by pgkiller** [comment]
🙃 手机上点完Comment返回刷新

**Comment by pgkiller** [comment]
不自动返回刷新

**Comment by pboymt** [comment]
物理按键都是要root的

**Comment by hyb1996** [comment]
该函数是不需要root的。实际测试中back()变成显示最近任务吗？

**Comment by pgkiller** [comment]
是的，显示最近任务

**Comment by hyb1996** [comment]
该问题应该是定制ROM更改对无障碍服务的[performGlobalAction](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService.html#performGlobalAction(int)) 函数的行为的修改，暂时没有办法"修复"。
