### ISSUE TITLE
TextView显示有字但id().findOne().text()获取不到字体

### ISSUE THREAD

**Issue by HELLKING66666** [hyb1996/Auto.js#300]
Samsung Note 3, Lineage os 14(7.1.1)

**Comment by HELLKING66666** [comment]
3.0Alpha40的apk

**Comment by hyb1996** [comment]
请尝试用id全名（例如`id("com.stardust.scriptdroid:id/text")`）获取，或者检查同个界面是否有其他相同id的控件

**Comment by HELLKING66666** [comment]
没有同名的呢，待会试试。布局层次翻看好几次了；另外微信的LinearLayout里面的控件在布局分析里并不能显示子控件的？android这方面，不太熟悉。

**Comment by HELLKING66666** [comment]
主要是APP内的控件基本翻了个透，就是没看有相关text的控件，获取的textView控件除了text为Null，其他正常

**Comment by hyb1996** [comment]
用布局分析工具查看后的控件的text属性是空的吗

**Comment by HELLKING66666** [comment]
是的，基本上确定没有其他控件了～请问下稳定模式与常规有何不同～:)

**Comment by hyb1996** [comment]
如果是布局工具查看也是Text为空的话，这个就不是软件的bug了。这样的情况是没法解决的， 可能是软件TextView是一个自定义的TextView。
稳定模式开启的时候有说明，懒得再打一遍了。

**Comment by HELLKING66666** [comment]
就是目前autojs不支持自定义控件。稳定模式开启我这边没弹窗。
工具还是很棒的，谢谢。

**Comment by HELLKING66666** [comment]
但发现，基本上都是android.widget.textView类的控件，不像是自定义的，其余控件文本很正常，作者可以提供下解决思路，我去捣鼓捣鼓，万分感谢～  ：）

**Comment by hyb1996** [comment]
可以到这里下载最新版https://www.coolapk.com/apk/129872
如果一个控件是自定义TextView, 也会显示为android.widget.TextView的。
也不是说不支持自定义控件，取决于控件是如何自定义的。
这个问题没有解决思路，如果能告诉一下具体是哪个软件的哪个界面我可以看一下。

**Comment by HELLKING66666** [comment]
冲顶大会的答题界面，如果有空可以看看，没空就算啦～

**Comment by hyb1996** [comment]
Soga，应该他实际上是一个WebView，也就是一个网页，所以出现无障碍支持不完全的情况很正常。
如果网页能在其他浏览器打开，例如chrome，可能就可以解决这个问题

**Comment by HELLKING66666** [comment]
autojs使用的界面解析工具是什么？啊啊啊？不是很懂为啥会被解析成textView而不是webView,app内的怎么变成在网页打开，原谅我愚蠢的智商

**Comment by HELLKING66666** [comment]
对了，能不能加快js的解析支持？好像很多内置函数、对象用不了，还有点文档更新的问题，有些函数没有～Alpha40的apk测的。辛苦作者啦

**Comment by boedge** [comment]
能获取到webview的url就好了

**Comment by hyb1996** [comment]
WebView支持无障碍啊，里面的文本会被解析为TextView。另外！不排除冲顶大会为了避免被抓取屏蔽了无障碍获取文本的情况。
app内的网页需要抓包获取链接。
js使用rhino引擎，参考文档的Overview。
文档里写的函数没有那是你没有更新最新版又看了在线文档....上面已经说了在那个链接下载最新版本。

**Comment by DoGoodMore** [comment]
@hyb1996 大佬 我现在是用布局分析出能看见text的正确值,
但是我用findOne().text()在log里输出就是'---'
初始值是'---',
场景是进入界面的时候有个用户名是'---', 然后点击查看用户名之后发请求获取后替换了textView的文本内容, 布局分析上是请求之后的内容， 但是findOne.text()还是那个初始值
