### ISSUE TITLE
如何了解autojs的原理？

### ISSUE THREAD

**Issue by DanteAndroid** [hyb1996/Auto.js#304]
究竟是怎样用js脚本来实现android原声代码一样的效果的？
简单易用的API是如何封装的？apk导出又是如何实现的？
小白一个，希望作者不吝赐教！

**Comment by pboymt** [comment]
Rhino或者J2V8作为JavaScript引擎，中间层绑定JavaScript的变量方法到Java的方法上面，然后脚本被解析的时候就会调用Java写的本地方法实现自动化了

**Comment by hyb1996** [comment]
Auto.js的核心参见 https://github.com/hyb1996/Auto.js/tree/master/autojs/src/main/java/com/stardust/autojs
其中 runtime.api的包便是各种api的封装。
至于apk打包，参见 https://github.com/hyb1996/Auto.js-ApkBuilder 。
