### ISSUE TITLE
如何点击桌面图标？

### ISSUE THREAD

**Issue by yuyang0** [hyb1996/Auto.js#310]
微信的小程序和公众号都可以设置桌面图标，怎么通过autojs点击桌面图标进入小程序？

**Comment by hyb1996** [comment]
分析桌面的布局。这个因每个桌面不同而不同。
例如在MIUI默认桌面下，要点击名字为"Auto.js"的图标：
```
desc("Auto.js").clickable().click();
```

**Comment by yuyang0** [comment]
@hyb1996 请问用autojs操作微信有封号的危险吗？

**Comment by hyb1996** [comment]
这个我猜没有
