### ISSUE TITLE
如何打开项目

### ISSUE THREAD

**Issue by TMLAndroid** [hyb1996/Auto.js#311]
请问，使用Android Studio 打开项目么，用AS打开会报错

**Comment by hyb1996** [comment]
AS不就是Android Studio 吗
我是用Android Studio 开发的，可能需要修改代理设置

**Comment by TMLAndroid** [comment]
``` gradle
Error:Unable to resolve dependency for ':app@coolapkDebug/compileClasspath': Could not resolve org.androidannotations:androidannotations-api:4.3.1.
Error:Unable to resolve dependency for ':app@coolapkDebug/compileClasspath': Could not resolve com.jakewharton:butterknife:8.6.0.
......
```
gradle编译报错，需要修改什么么

**Comment by TMLAndroid** [comment]
另外，请问大佬，我有三个问题请教你（这方面菜鸟一个，希望不惜赐教）

1. 这个是混合开发还是什么其他方式的，我看你的ui界面时用js写的，感觉好高级的样子。
2. 可以简单介绍一些是怎么实现不需要root或者连接usb数据线就能实现uiautomator获取界面控件
3. 还有，可以简单介绍一下各个依赖module的功能么（autojs,automator,common）
非常感谢大佬的解疑答惑（PS:有交流群么）

**Comment by hyb1996** [comment]
1. 这个软件的ui界面并不是由js写的。是这个软件提供了一个可以编写界面的js环境。这个软件本身的界面是由Java和Android XML编写的。
2. 这是利用了AccessibilityService的API。参见[AccessibilityService](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService.html)的getRootInActivieWindow()函数。
3.
* common模块提供了其他各个模块的公用类、工具等，例如一些数据结构、View工具类等。是其他各个模块的依赖。
* automator模块实现了自动操作的大部分内容。包括选择器的实现、简单操作的实现、控件节点的封装等。是autojs模块的依赖。
* autojs模块是Auto.js的JavaScript运行环境，包括脚本引擎的封装，核心运行库的实现，对JavaScript层暴露的API，JavaScript和Java的交互。同时提供了管理运行的JavaScript脚本的服务。
* app模块是界面、业务逻辑。依赖autojs模块。
4. 本项目主要需要Android基础，和uiautomator基础没有太大关系。
交流群：586823180

**Comment by hyb1996** [comment]
关于编译项目的问题，因为一些依赖需要翻墙才能下载，所以需要准备VPN，然后在项目的gradle.properties文件修改代理端口和地址。

**Comment by TMLAndroid** [comment]
非常谢谢大佬，设置了代理和端口，已经可以运行了。
大佬你说界面通过xml和java编写，那，项目下的app/sample/界面控件/输入框控件.js下的代码
和apk展示的布局一样的，有什么关系呢，看上去就是描述这个界面
```javascript
"ui";

ui.layout(
    <vertical padding="16">
         <text text="输入框" textColor="black" textSize="16sp" marginTop="16"/>
         <input />

         <!-- hint属性用来设置输入框的提示-->
         <text text="带提示的输入框" textColor="black" textSize="16sp" marginTop="16"/>
         <input hint="请输入一些内容"/>

         <!-- inputType属性用来设置输入类型，包括number, email, phone等-->
         <text text="数字输入框" textColor="black" textSize="16sp" marginTop="16"/>
         <input inputType="number" text="123"/>

         <!-- password属性用来设置输入框是否是密码输入框 -->
         <text text="密码输入框" textColor="black" textSize="16sp" marginTop="16"/>
         <input password="true"/>

         <!-- lines属性用来设置输入框的行数 -->
         <text text="多行输入框" textColor="black" textSize="16sp" marginTop="16"/>
         <input lines="3"/>

         <text text="设置输入框错误信息" textColor="black" textSize="16sp" marginTop="16"/>
         <input id="qq" inputType="number" hint="请输入您的QQ号码"/>
         <button id="ok" text="确定" w="auto" style="Widget.AppCompat.Button.Colored"/>
    </vertical>
);

ui.ok.click(()=>{
    var text = ui.qq.text();
    if(text.length == 0){
        ui.qq.setError("输入不能为空");
        return;
    }
    var qq = parseInt(text);
    if(qq < 10000){
        ui.qq.setError("QQ号码格式错误");
        return;
    }
    ui.qq.setError(null);
});

```

**Comment by hyb1996** [comment]
这个只是一个示例脚本。不是构成本软件界面的脚本。
他确实是显示一个界面，但是必须依赖本软件运行。
这些标签大多是自定义的，并通过Auto.js把它解析为布局。
和Android的界面编写不是一回事。

**Comment by TMLAndroid** [comment]
明白了，大佬你自己写了一个布局解析，把js解析成Android可以展示的界面，牛逼了！
