### ISSUE TITLE
打包应用的apk似乎同autojs不一样

### ISSUE THREAD

**Issue by skyearthfeng** [hyb1996/Auto.js#315]
感谢大神，写的脚本在autojs中运行正常，打包后执行过程中经常找不到控件点击。

**Comment by Constantine1949** [comment]
我也发现了这个问题，我这边打包出来的apk是inrt，运行显示“打包出错了~使用文件夹打包请把主脚本改民为main.js”，这个怎么解决呀

**Comment by JustForSmiling** [comment]
我用的是8.x的pro版本，今天也出现这个问题了，调试过程中一直都可以，打包的APK中却找不到控件，郁闷死了
