### ISSUE TITLE
请教大佬，有个类找不到，还有打包问题

### ISSUE THREAD

**Issue by Constantine1949** [hyb1996/Auto.js#316]
1.GlideApp
![1](https://user-images.githubusercontent.com/17808758/37460786-44f720e6-2887-11e8-87e6-5daa28a8e973.png)
![2](https://user-images.githubusercontent.com/17808758/37460790-4740963e-2887-11e8-82ee-ac21ba57f3b6.png)
![3](https://user-images.githubusercontent.com/17808758/37460792-4932815a-2887-11e8-98f3-ce2f15c31700.png)
看样子直接用Glide也一样？

2.打包成这样，该怎么有效的解决
![119554d96c7d123273772cb210ecb355](https://user-images.githubusercontent.com/17808758/37461162-77db89e2-2888-11e8-8bf4-538ba2ce4929.png)
![c99780693ac2e33f0fbc023ab3cbb980](https://user-images.githubusercontent.com/17808758/37461177-7d7ad02e-2888-11e8-9897-e4f70bc8bb6c.png)

**Comment by Constantine1949** [comment]
测试一楼，好像又找到了，Amazing
![4](https://user-images.githubusercontent.com/17808758/37461548-a28d65a6-2889-11e8-8f2a-fe52395a8979.png)

**Comment by hyb1996** [comment]
GlideApp是编译后会自动生成的类。
至于inrt。把Android Studio "运行"图标左边的inrt改成app再运行即可。

**Comment by shuyabin** [comment]
@Oreo1995  大佬有碰到这样的问题嘛？
![image](https://user-images.githubusercontent.com/14884581/64908766-b23c1a80-d736-11e9-87a6-7577ed2e32df.png)
