### ISSUE TITLE
如何复用js文件？

### ISSUE THREAD

**Issue by jasontujun** [hyb1996/Auto.js#319]
有好几个js文件，有大量的方法是重复的。请问在autojs里怎样能把这些重复的方法抽出来复用？好像每一个脚本文件都是独立加载运行的，在一个文件夹中的几个脚本文件，也没法互相调用方法

**Comment by pboymt** [comment]
你可以把重复方法单独写一个文件里面然后用`module.exports`导出，然后在需要引用的文件里面用 `require` 方法导入。
你还可以用我的autojs-dev工具把所有脚本文件编译成一个单一文件来执行，也可以复用方法

**Comment by hyb1996** [comment]
使用模块。参见文档的模块章节。

**Comment by jasontujun** [comment]
好的。懂了！我这边从华为应用市场下载的，版本还是2.0.16，太老了，我更新下
