### ISSUE TITLE
请问是否能够根据文字获取界面上文字对应的坐标位置？

### ISSUE THREAD

**Issue by MrCWei** [hyb1996/Auto.js#320]

**Comment by hyb1996** [comment]
var t = text("文字").findOne();
log(t.bounds().left, b.bounds().top);

**Comment by MrCWei** [comment]
报错了
14:33:22.435/E: TypeError: Cannot find function bound in object com.stardust.automator.UiObject@801f4af9; boundsInParent: Rect(0, 0 - 90, 61); boundsInScreen: Rect(0, 1823 - -439, 1884); packageName: com.stardust.scriptdroid; className: android.widget.TextView; text: 设置; contentDescription: null; viewId: null; checkable: false; checked: false; focusable: false; focused: false; selected: false; clickable: false; longClickable: false; enabled: true; password: false; scrollable: false; [ACTION_SELECT, ACTION_CLEAR_SELECTION, ACTION_ACCESSIBILITY_FOCUS, ACTION_NEXT_AT_MOVEMENT_GRANULARITY, ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY, ACTION_SET_SELECTION]. (<Qq>#2)
	at script(<Qq>:2)

**Comment by Ancientwood** [comment]
邮件收到「报错了」三个字内心可耻地抖了一抖（以为项目邮件😂（吐槽

**Comment by hyb1996** [comment]
是bounds不是bound

**Comment by MrCWei** [comment]
请问这些相关的api在哪里可用查到？想自己做做脚本，哪里可用查接口？

**Comment by pboymt** [comment]
楼上你会提issue不会看readme吗🙄

**Comment by hyb1996** [comment]
https://hyb1996.github.io/AutoJs-Docs/
