### ISSUE TITLE
请问autojs如何刷新图库

### ISSUE THREAD

**Issue by xifumengmengda** [hyb1996/Auto.js#321]

**Comment by xifumengmengda** [comment]
或者说是不能实现这个功能的吗

**Comment by pboymt** [comment]
Media模块有这个功能

**Comment by xifumengmengda** [comment]
在安卓安卓6.0上面调试会出现这个问题，请问是怎么回事呢？autojs调试版本是3.0.0Alpha34
![666](https://user-images.githubusercontent.com/16473366/37957256-05da2a56-319d-11e8-8bda-d314798d699c.png)

**Comment by pboymt** [comment]
scanfile只能触发本地图片的识别，你可以先用images.load下载图片，然后img.saveTo保存图片，然后把保存路径用scanfile触发图库扫描

**Comment by xifumengmengda** [comment]
@pboymt 谢谢你的提醒，但是我测试了还是不行，我是安卓6.0的，是不是这个原因呢，提示的还是media is not defined
![666](https://user-images.githubusercontent.com/16473366/37958770-e920d5f0-31a0-11e8-9810-f839e90f78e6.png)

**Comment by hyb1996** [comment]
Auto.js版本过低导致的
media模块是某一个版本添加的

**Comment by hyb1996** [comment]
加入内测群获取最新版本586823180

**Comment by xifumengmengda** [comment]
@hyb1996 好的，谢谢
