### ISSUE TITLE
调用Keys.Power()提示Keys is not define 

### ISSUE THREAD

**Issue by JamesLebron** [hyb1996/Auto.js#322]
作者你好，我想实现锁屏功能，调用Keys.Power()提示Keys 未定义，调用keys.Power();提示 找不到那个方法，应该不是keys这个对象吧
已经看过您的官方API，调用方式好像就是这样的吧
手机已经ROOT

**Comment by hyb1996** [comment]
Power()，全局函数。
如果是keys对象的函数的话文档会写"keys.Power()"而不是只写"Power()"。
