### ISSUE TITLE
内存会随着脚本运行一直上升而不会出现下降

### ISSUE THREAD

**Issue by pboymt** [hyb1996/Auto.js#323]
脚本运行多了就会出现这个问题，是不是运行时缓存不会自动清理啊？而且从来不释放，一般都保持在350兆到600兆，手机就会特别卡了。

**Comment by hyb1996** [comment]
我最近也注意到了内存泄漏问题。目前发现可能有以下两个问题：
1. AccessibilityNodeInfo没有回收，也就是UiObject没有得到回收。在以前版本的Auto.js中曾经尝试过主动及时回收，但一些AccessibilityNodeInfo对象是系统给出的，如果对他进行回收而系统之后再回收一次会导致崩溃。目前是不主动回收等待finalize方法回收。
2. 找图功能基于Opencv，可能存在使用native对象的内存泄漏问题。

以上问题我尽快查明和修复。

**Comment by pboymt** [comment]
我可以确定我遇到的问题是找图的内存泄漏，我的脚本大量使用找图功能。我已经自己写了运行时素材缓存了，如果没有写可能会更严重

**Comment by hyb1996** [comment]
已确认找图存在内存泄漏。将会修复。
