### ISSUE TITLE
aosip 8.1 辅助服务存在未知问题

### ISSUE THREAD

**Issue by venssy** [hyb1996/Auto.js#324]
aosip 8.1 开启辅助服务后，屏幕无法接收触摸事件，相当于加了个阻挡图层，触摸失效，实体键没有问题，logcat没有得到有效信息，在pixel上也有这个问题（出问题几率80%）

**Comment by hyb1996** [comment]
没有其他Bug报告，猜测是已经不存在的问题，故关闭这个issue
