### ISSUE TITLE
希望完善UI文档并为控件添加EventListener

### ISSUE THREAD

**Issue by pboymt** [hyb1996/Auto.js#333]
现在click和longClick不够用啊，希望增加change这样的事件。最好有addEventListener或on及它们的对应方法。
还有控件的属性方法只有_id、click和longClick可以枚举，其他的都无法枚举，对调试造成很大不便。

**Comment by pboymt** [comment]
最好有addEventListener或on及它们的对应方法

**Comment by hyb1996** [comment]
目前有 touch_down, touch, click, longClick, single_tap, show_press, scroll, fling, key等事件。
这几天会增加其他更多事件和文档。

**Comment by pboymt** [comment]
好，期待
