### ISSUE TITLE
Auto.js本身可能存在内存泄漏

### ISSUE THREAD

**Issue by pboymt** [hyb1996/Auto.js#334]
如果不强制清理进程的话，每次打开Auto.js，占用的内存都会增加，退出后也不下降。包括UI脚本也会造成同样的后果。是不是Activity离开后内存不会被自动回收？

**Comment by baskgithub** [comment]
same issue

**Comment by e1399579** [comment]
@hyb1996 建议提高稳定性、减少内存占用，优先级应该比新功能高

**Comment by hyb1996** [comment]
已修复
