### ISSUE TITLE
脚本存放目录能否自定义

### ISSUE THREAD

**Issue by langrenfengzi** [hyb1996/Auto.js#335]
Auto.js 有做中英文适配，中文的话默认是在SDCard的"脚本"目录，英文的则是"Scripts"目录。
平常用的时候会切换手机语言环境，会导致英文环境下Scripts目录里存放的脚本在中文环境下找不到，导入的话只能一个一个的脚本导入，而且是复制了一份。
如果能自定义存放目录，并记住路径，就非常方便了。
谢谢！

**Comment by hyb1996** [comment]
已支持 https://github.com/hyb1996/Auto.js/commit/023b8a79d984e150d9aa760c8e4930a0d4d00287
