### ISSUE TITLE
为何有些webview无法进行布局分析

### ISSUE THREAD

**Issue by joriscai** [hyb1996/Auto.js#344]
为什么有些webview无法进行布局分析呢？能不能提供一些方法来直接获得webview里面的html字符串呢？

**Comment by guoyitao** [comment]
后来用什么方式解决了啊

**Comment by nckf** [comment]
> 为什么有些webview无法进行布局分析呢？能不能提供一些方法来直接获得webview里面的html字符串呢？

尝试 `OCR` ？

**Comment by qninth** [comment]
想问，一样遇到这个问题
