### ISSUE TITLE
博主编译通不过什么原因 少了好多依赖 

### ISSUE THREAD

**Issue by yinhuahua** [hyb1996/Auto.js#345]
Failed to resolve: com.github.atlassian:commonmark-java:commonmark-parent-0.9.0 Show in FileShow in Project Structure dialog |  
-- | --
Failed to resolve: com.heinrichreimersoftware:android-issue-reporter:1.3.1 Show in FileShow in Project Structure dialog |  
Failed to resolve: com.github.hyb1996:android-multi-level-listview:1.1 Show in FileShow in Project Structure dialog |  
Failed to resolve: com.github.hyb1996:FloatingCircularActionMenu:0.0.4 Show in FileShow in Project Structure dialog |  
Failed to resolve: com.github.hyb1996:Auto.js-ApkBuilder:1.0.1 Show in FileShow in Project Structure dialog |  
Failed to resolve: com.github.Raizlabs.DBFlow:dbflow-core:4.1.2 Open FileShow in Project Structure dialog |  
Failed to resolve: com.github.Raizlabs.DBFlow:dbflow:4.1.2 Open FileShow in Project Structure dialog |  
Failed to resolve: com.github.Raizlabs.DBFlow:dbflow-rx2:4.1.2 Open FileShow in Project Structure dialog |  
Failed to resolve: com.github.hyb1996:settingscompat:1.1.5 Open FileShow in Project Structure dialog |

**Comment by hyb1996** [comment]
在根目录的gradle.properties文件中删除代理的设置，或者自己设置代理

**Comment by cloudqq** [comment]
代理害人啊，折腾了好几个小时 :(
