### ISSUE TITLE
clip()函数有问题？

### ISSUE THREAD

**Issue by joriscai** [hyb1996/Auto.js#346]
`
function clipImg() {
    console.log('clipImg')
    var img = captureScreen();
    sleep(100);
    console.log(img);
    var clip = images.clip(img, 118, 814, 836, 880);
    return clip;
}
`

上面的代码，在不同的文件上，有些会报异常，异常是Bitmap.getWidth()的空指针异常，这个要怎么解决？

异常日志
01:33:55.603/E: Wrapped java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference (<<remote>:autoAnswer-normal3>#105)
 at script.clipImg(<<remote>:autoAnswer-normal3>:105)
 at script(<<remote>:autoAnswer-normal3>:68)

**Comment by hyb1996** [comment]
是captureScreen()返回null的问题，已经修复~
