### ISSUE TITLE
toast只能在auto.js中显示，其他软件界面不显示

### ISSUE THREAD

**Issue by wally94** [hyb1996/Auto.js#351]
toast只能在auto.js中显示，其他软件界面不显示是个例吗？

**Comment by hyb1996** [comment]
华为手机中限制了toast的显示

**Comment by wally94** [comment]
我的是oppo ，看了也是限制了

**Comment by xiaofeng930415** [comment]
华为手机7.0的无法显示，8.0可以显示；小米手机7.1.2的，可以显示，但不实时，会在脚本的主要逻辑执行完毕后集中显示，略无语，还不如没有。用的是toastLog。

**Comment by hyb1996** [comment]
@xiaofeng930415 toast本身就是异步的，参见toast函数的文档。如果要同步显示需要自行设置延时。

**Comment by xiaofeng930415** [comment]
是我忽略了。

**Comment by start201711** [comment]
努比亚也被限制了
