### ISSUE TITLE
关于 put请求的问题

### ISSUE THREAD

**Issue by wally94** [hyb1996/Auto.js#354]
[Extension Host] 14:26:31.958/E: TypeError: writeTo is not a function, it is object. (__http__.js#44)
	at script(__http__.js:44)
	at script(<<remote>:c:\Users\WALLY\Documents\check>:64)

出现这样的提示是为什么？
下面是我使用的时候
var res=http.request("http://192.168.1.100/index/"+data[i].id,
{method:"PUT",
body:{
        key: "65458a5df537443b89b31f1c03202a80",
        info: "你好啊",
        userid: "1",
    }})

**Comment by hyb1996** [comment]
PUT不能像POST直接使用键值对。
```
function putFormEncoded(url, options){
    var body = new okhttp3.FormBody.Builder();
    for(var key in options.body){
         if(data.hasOwnProperty(key)){
            body.add(key, data[key]);
         }
     }
    options.body = body.build();
    options.contentType = "application/x-www-form-urlencoded";
    options.method = "PUT";
   return http.request(url, options);
}


var res=putFormEncoded("http://192.168.1.100/index/"+data[i].id,
{
body:{
key: "65458a5df537443b89b31f1c03202a80",
info: "你好啊",
userid: "1",
}})
```

**Comment by wally94** [comment]
好的  谢谢你
