### ISSUE TITLE
如何默认设置脚本的稳定模式？3个子问题。

### ISSUE THREAD

**Issue by xiaofeng930415** [hyb1996/Auto.js#355]
因为自己的脚本是在稳定模式下开发的，但每次安装后都需要设置一下，经常因忘记，而导致出错。
1，能否在打包前通过修改默认配置，改变默认值。
2，能否在运行脚本时，动态检测+修改？如果可以，是通过xml记录还是手机存储实现。
3，控制脚本去自动点击，已经试过了，不可行，应该是打包脚本默认设置了不可在本脚本界面操作的缘故。

**Comment by hyb1996** [comment]
在脚本前面加上
```
var pref = android.content.SharedPreferences.getDefaultSharedPreferences(context);
pref.edit().putBoolean("key_stable_mode", true).apply();
```

**Comment by hyb1996** [comment]
后面会加上打包默认设置

**Comment by xiaofeng930415** [comment]
感谢回复~

**Comment by toblessing** [comment]
> 在脚本前面加上
> 
> ```
> var pref = android.content.SharedPreferences.getDefaultSharedPreferences(context);
> pref.edit().putBoolean("key_stable_mode", true).apply();
> ```
使用了这两行会提示这个，是哪里弄错了吗？
class "android.content.SharedPreferences" has no public instance field or method named "getDefaultSharedPreferences".

**Comment by toblessing** [comment]
> > 在脚本前面加上
> > ```
> > var pref = android.content.SharedPreferences.getDefaultSharedPreferences(context);
> > pref.edit().putBoolean("key_stable_mode", true).apply();
> > ```
> 
> 使用了这两行会提示这个，是哪里弄错了吗？
> 类“android.content.SharedPreferences”没有名为“getDefaultSharedPreferences”的公共实例字段或方法。

然后我使用这两行就可以了
var pref = android.preference.PreferenceManager.getDefaultSharedPreferences(context);
pref.edit().putBoolean("key_stable_mode", true).apply();
