### ISSUE TITLE
[Enhancement] Does Auto.js support ECMA6 till now? The Key word "class" is not supported yet.

### ISSUE THREAD

**Issue by baskgithub** [hyb1996/Auto.js#356]
The engine Rhino 1.7.7.2 does not support ECMA6 completely.
It's a little weird to define a class using "function".

**Comment by pboymt** [comment]
You can use [autojs-dev](https://github.com/pboymt/autojs-dev) compile typescript to ES5. But this tool only support Chinese and you can view my code to learn how to compile the typescript file.

**Comment by XeroAlpha** [comment]
See [mozilla/rhino issue#434](https://github.com/mozilla/rhino/issues/434)

**Comment by XeroAlpha** [comment]
See [mozilla/rhino issue#434](https://github.com/mozilla/rhino/issues/434)

**Comment by cloudqq** [comment]
It's easy with webpack and babel.
