### ISSUE TITLE
监听控件变化的线程

### ISSUE THREAD

**Issue by start201711** [hyb1996/Auto.js#358]
监听控件变化的线程和脚本执行的线程不是在同一个线程吧？onAccessibilityEvent这个是在主线程里面的吧，而脚本是在自己开的线程里面的。那么，seletor.findOne()不会卡死主线程吗？

**Comment by start201711** [comment]
@Override
public void onAccessibilityEvent(final AccessibilityEvent event) {
    instance = this;
    Log.v(TAG, "onAccessibilityEvent: " + event);
    if (!containsAllEventTypes && !eventTypes.contains(event.getEventType()))
        return;
    int type = event.getEventType();
    if (type == AccessibilityEvent.TYPE_WINDOW_STATE_CHANGED ||
            type == AccessibilityEvent.TYPE_VIEW_FOCUSED) {
        AccessibilityNodeInfo root = super.getRootInActiveWindow();
        if (root != null) {
            mFastRootInActiveWindow = root;
        }
    }

    for (Map.Entry<Integer, AccessibilityDelegate> entry : mDelegates.entrySet()) {
        AccessibilityDelegate delegate = entry.getValue();
        Set<Integer> types = delegate.getEventTypes();
        if (types != null && !delegate.getEventTypes().contains(event.getEventType()))
            continue;
        //long start = System.currentTimeMillis();
        if (delegate.onAccessibilityEvent(AccessibilityService.this, event))
            break;
        //Log.v(TAG, "millis: " + (System.currentTimeMillis() - start) + " delegate: " + entry.getValue().getClass().getName());
    }
}

**Comment by hyb1996** [comment]
selector.findOne()是在子线程执行的
