### ISSUE TITLE
源代码中是否可以增加opencv库的x86库，方便在windows模拟器中调试

### ISSUE THREAD

**Issue by cloudqq** [hyb1996/Auto.js#362]
@hyb1996 

compile 'com.github.hyb1996:OpenCvLib:2.4.13.4-imgproc'

我发现opencv是你自己封装的库，因为没有提供源码，所以也没有办法自己搞一份。 所以请帮忙提供一份x86的库， 方便在windows 模拟器上进行相关的调试和测试。

**Comment by hyb1996** [comment]
OpencvLib在这里https://github.com/hyb1996/OpenCvLib，
至于x86的动态链接库，在这里https://sourceforge.net/projects/opencvlibrary/files/opencv-android/2.4.13/ 下载2.4.13.4的opencv android sdk，压缩包内的sdk/native/lib里面有你需要的
