### ISSUE TITLE
提示无悬浮窗权限

### ISSUE THREAD

**Issue by zlsq** [hyb1996/Auto.js#363]
机型:小米6
系统:MIUI9
问题:打开软件即提示无悬浮窗权限, 但是在左侧悬浮窗按钮我已经打开, 相应权限也已经给了.
版本:3.1.0 Beta 酷安下载

**Comment by hyb1996** [comment]
已经在https://github.com/hyb1996/Auto.js/commit/220473c109657e8f8d744219fc314d8c8eff206e 中修复
