### ISSUE TITLE
开启无障碍服务导致按键失灵

### ISSUE THREAD

**Issue by oe77** [hyb1996/Auto.js#366]
系统：MIUI 10       MIUI 8.5
手机型号： 小米5s plus     红米4x
版本号：Auto.js 4.0   Auto.js 3.0 

问题：首次运行Auto.js，并开启无障碍服务，按键不会失灵，一切正常！但当退出Auto.js再进，菜单按键，主页键，返回键，这三个键马上失灵！关机键正常！

解决方法：关掉Auto.js的无障碍服务

这个问题折腾我好旧了，我以为4.0会修复！

**Comment by oe77** [comment]
就是后台完全退出Auto.js应用，再次进入Auto.js时，按键会失效

**Comment by oe77** [comment]
按键失灵，这个问题好多人在酷安反应过了

**Comment by hyb1996** [comment]
可以加一下群586823180沟通一下~

**Comment by hyb1996** [comment]
@aizya 安全指的是哪一方面

**Comment by aizya** [comment]
支付密码之类的.

**Comment by hyb1996** [comment]
本软件开源保证了安全性；但除此之外，不要运行恶意脚本，或者脚本要看一下内容再运行。不过国内的支付宝等应用在这方面还是做的比较好的，无障碍是无法获取密码的。

**Comment by aizya** [comment]
谢谢

**Comment by hello0word** [comment]
我也遇到了  小米6  miui 10
