### ISSUE TITLE
下载打包插件提示504

### ISSUE THREAD

**Issue by lucky9322** [hyb1996/Auto.js#377]
你好，写好脚本之后 选择进行打包apk提示需要下载打包插件，进行跳转下载时 504

https://i.autojs.org/autojs/plugin/204.apk

**Comment by hyb1996** [comment]
在这里下载 https://www.coolapk.com/apk/178717

**Comment by lucky9322** [comment]
OK 谢谢，另外auto.js在模拟器上支持吗，我在7.1genymotion模拟器上启动之后直接显示的应用设置详情

**Comment by hyb1996** [comment]
已经修复

**Comment by weathon** [comment]
现在似乎也下载不了了
