### ISSUE TITLE
4.0.2Alpha9，大概每天崩溃一次

### ISSUE THREAD

**Issue by cqman2** [hyb1996/Auto.js#378]
Version: 414
Android: 27
java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
java.lang.Thread.nativeCreate(Native Method)
java.lang.Thread.start(Thread.java:753)
java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1611)
java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:342)
java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:579)
java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:680)
io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:146)
io.reactivex.internal.schedulers.IoScheduler$EventLoopWorker.schedule(IoScheduler.java:230)
io.reactivex.Scheduler$Worker.schedule(Scheduler.java:272)
io.reactivex.internal.operators.flowable.FlowableSubscribeOn.subscribeActual(FlowableSubscribeOn.java:48)
io.reactivex.Flowable.subscribe(Flowable.java:12995)
io.reactivex.internal.operators.flowable.FlowableObserveOn.subscribeActual(FlowableObserveOn.java:56)
io.reactivex.Flowable.subscribe(Flowable.java:12995)
io.reactivex.Flowable.subscribe(Flowable.java:12931)
io.reactivex.Flowable.subscribe(Flowable.java:12821)
org.autojs.autojs.timing.TimedTaskScheduler.checkTasks(TimedTaskScheduler.java:45)
org.autojs.autojs.timing.TimedTaskScheduler.onReceive(TimedTaskScheduler.java:36)
android.app.ActivityThread.handleReceiver(ActivityThread.java:3642)
android.app.ActivityThread.-wrap18(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1985)
android.os.Handler.dispatchMessage(Handler.java:109)
android.os.Looper.loop(Looper.java:166)
android.app.ActivityThread.main(ActivityThread.java:7377)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by hyb1996** [comment]
最新版已经修复，请加群：586823180
