### ISSUE TITLE
请问wx消息跟QQ消息，控件由textview更改成view无法获取文本

### ISSUE THREAD

**Issue by learder** [hyb1996/Auto.js#384]
请问wx消息跟QQ消息，控件由textview更改成view无法获取文本。有可行的思路吗？这种通过强转，能否达到目的呢？

**Comment by hyb1996** [comment]
一个可行的方法是，截图，截取控件范围的图片，OCR

**Comment by shengqiangzhang** [comment]
采用长按复制 目前只能这样，具体函数可以看开发文档，采用OCR方式识别或多或少会不准
