### ISSUE TITLE
请教Point的使用

### ISSUE THREAD

**Issue by xinyu3ru** [hyb1996/Auto.js#385]
文档中
```
Point
findColor, findImage返回的对象。表示一个点（坐标）。
```
可以看到Point的格式是 {42.0, 875.0} 这样的一个对象？
可是我不会点击这个点，请教怎样才能点击这个点的坐标
![image](https://user-images.githubusercontent.com/3859309/47092999-c5aae100-d25a-11e8-8546-eedcc581a16d.png)

**Comment by hyb1996** [comment]
press(p.x, p.y)应该是可行的吧，你是遇到什么错误吗

**Comment by xinyu3ru** [comment]
`06:32:00.084/E: Can't find method com.stardust.autojs.core.accessibility.SimpleActionAutomator.press(number,number).
    at dakarukou (/storage/emulated/0/脚本/x.js:40:0)
    at /storage/emulated/0/脚本/x.js:9:0
- - - - - - - - - - -

org.mozilla.javascript.EvaluatorException: Can't find method com.stardust.autojs.core.accessibility.SimpleActionAutomator.press(number,number). (/storage/emulated/0/脚本/x.js#40)
at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
at`


press 操作不行，但是今天突然想用click试一下，结果click是没有问题的。

![image](https://user-images.githubusercontent.com/3859309/47122482-8ce62880-d2a9-11e8-806d-0d00be725ddd.png)

@hyb1996

**Comment by hyb1996** [comment]
press需要加上按住时长,
```
press(p.x, p.y, 100);
```

**Comment by xinyu3ru** [comment]
@hyb1996 谢谢
