### ISSUE TITLE
打包apk有教程吗，另外想引用其他jar包，jar包放哪才能进classpath

### ISSUE THREAD

**Issue by wang1784594241** [hyb1996/Auto.js#387]
是不是不打包apk引用不了呢

**Comment by hyb1996** [comment]
在脚本中就能直接使用jar
runtime.loadJar(路径) （最新版本）

**Comment by wang1784594241** [comment]
> 在脚本中就能直接使用jar
> runtime.loadJar(路径) （最新版本）

谢谢，那打包apk做成小应用怎么弄呢，只能我本地运行Auto.js-ApkBuilder这个项目才行吗

**Comment by wang1784594241** [comment]
谢谢，刚看到这个https://www.coolapk.com/apk/178717 ，建议把这些信息放文档里
