### ISSUE TITLE
新增 插件（将提供OCR插件）

### ISSUE THREAD

**Issue by ninghaixin** [hyb1996/Auto.js#388]
请问什么时候可以使用这个插件？

**Comment by hyb1996** [comment]
已经开发出来但是速度过慢，因此没有放出来

**Comment by hyb1996** [comment]
@ninghaixin 是本地识别 用的是tessocr 由于没有对图片做处理（灰度化，二值化之类的），直接交给tessocr很慢，如果有时间的话可以帮忙改善

**Comment by ninghaixin** [comment]
我之前没做过这块 我先研究一下

**Comment by Nick-Hopps** [comment]
> 
> 
> @ninghaixin 是本地识别 用的是tessocr 由于没有对图片做处理（灰度化，二值化之类的），直接交给tessocr很慢，如果有时间的话可以帮忙改善

是用的 tesseract.js 吗？

**Comment by hyb1996** [comment]
> > @ninghaixin 是本地识别 用的是tessocr 由于没有对图片做处理（灰度化，二值化之类的），直接交给tessocr很慢，如果有时间的话可以帮忙改善
> 
> 是用的 tesseract.js 吗？

不是 是https://github.com/rmtheis/tess-two

**Comment by hyb1996** [comment]
@Nick-Hopps PC上的速度和手机上的可能有差距
我在小米6上一张1080*1920的灰度化图片需要十几秒时间识别

**Comment by Nick-Hopps** [comment]
@hyb1996 我的话是截图然后剪切再二值化再识别的。BTW，你怎么在手机上运行的？直接调用的话它默认加载的是远程的文件，速度很慢的

**Comment by hyb1996** [comment]
@Nick-Hopps 我指的是tess-two的速度。

**Comment by Nick-Hopps** [comment]
@hyb1996 哦哦这样，感觉 OCR 识别大图都很慢的样子
