### ISSUE TITLE
如何引用第三方jar文件？

### ISSUE THREAD

**Issue by lepon** [hyb1996/Auto.js#389]
比如读写数据库，需要第三方jar文件。。这个jar文件应该放到哪里，才可以在autojs的js代码中通过importPackage进来？

**Comment by hyb1996** [comment]
runtime.loadJar("路径");
或者
runtime.loadDex("路径");
注意使用4.0.4

**Comment by hyb1996** [comment]
你可以写个模块，自动加载某个目录的文件。开头时引用该模块就行了。
特定的需求并且这个需求可以通过简单的代码来实现的话，就不会为这个需求特别增加行为

**Comment by lepon** [comment]
> 想知道你是否成功导入了，我会出错。Wrapped com.stardust.pio.UncheckedIOException: java.io.FileNotFoundException: /data/user/0/org.autojs.autojs/cache/classes/11f8d85f57734......

太麻烦。。我没有做。。

**Comment by rob-in-the-house** [comment]
> 想知道你是否成功导入了，我会出错。Wrapped com.stardust.pio.UncheckedIOException: java.io.FileNotFoundException: /data/user/0/org.autojs.autojs/cache/classes/11f8d85f57734......

也遇到了 有的能成功 有的不行 找到原因了吗？

**Comment by lepon** [comment]
> > 想知道你是否成功导入了，我会出错.Wrapped com.stardust.pio.UncheckedIOException：java.io.FileNotFoundException：/data/user/0/org.autojs.autojs/cache/classes/11f8d85f57734 ..... 。
> 
> 也遇到了有的能成功有的不行找到原因了吗？

应该是jar包打包的原因，尽可能的找用android studio打的包，我本身不是移动应用开发人员，也不了解java。eclipse打包的基本上引用很容易报错

**Comment by hyb1996** [comment]
打包时指定Java版本为6
