### ISSUE TITLE
对应的打包插件工程在哪里

### ISSUE THREAD

**Issue by apgzs** [hyb1996/Auto.js#392]

**Comment by hyb1996** [comment]
打包插件其实里面只是一个apk而已

**Comment by apgzs** [comment]
打包插件的代码有开源吗

**Comment by hyb1996** [comment]
这个工程的inrt模块就是了，编译出来的apk替换打包插件的assets/template.apk即可。
不过后续支持打包加密时则不会开源

**Comment by apgzs** [comment]
打包插件的包名是 org.autojs.apkbuilderplugin  但是inrt工程的包名是com.stardust.auojs.inrt    我编译完inrt直接安装 app  和  inrt   打包的时候还是报没有打包插件的错误

**Comment by hyb1996** [comment]
打包插件在release页面安装。这个插件是通过构建脚本生成的，其实只是一个壳，里面只装着一个inrt这个apk，你可以下载一个插件解包一下就知道了

**Comment by apgzs** [comment]
那个官网的文档是最新的吗   有没有那种付费版的 可以享受更多服务的
