### ISSUE TITLE
[bug] 授权截图权限时崩溃

### ISSUE THREAD

**Issue by AgMonk** [hyb1996/Auto.js#395]
模拟器：BlueStacks+N 7.1
来源：https://www.52pojie.cn/thread-718637-5-1.html

症状，示例代码中requestScreenCapture函数运行后提示需要权限，如果不允许则无事发生，选择允许会导致卡死，不能进行任何操作只能重启模拟器。

尝试过凤凰OS，症状相同

**Comment by hyb1996** [comment]
提供一下日志

**Comment by jackdizhu** [comment]
![image](https://user-images.githubusercontent.com/17809883/53413480-084da880-3a07-11e9-8127-346e5c2e336f.png)

这个渲染模式 截图方法阻塞 OpenGL 可以
但是可以看下 DirectX 这个为什么不能截图吗

**Comment by hyb1996** [comment]
这个Auto.js没有办法解决

**Comment by Dwayneten** [comment]
遇到同样的问题
在模拟器设定 - 引擎 - 勾选使用高级图形引擎模式 解决了
