### ISSUE TITLE
findMultiColors 的问题

### ISSUE THREAD

**Issue by nkchwfree** [hyb1996/Auto.js#398]
调用这个方法的时候出现异常：
14:20:49.103/E: Wrapped CvException [org.opencv.core.CvException: cv::Exception: /build/2_4_pack-android/opencv/modules/core/src/matrix.cpp:296: error: (-215) 0 <= _colRange.start && _colRange.start <= _colRange.end && _colRange.end <= m.cols in function cv::Mat::Mat(const cv::Mat&, const cv::Range&, const cv::Range&)
] (__images__.js#123)
	at script(__images__.js:123)
	at script(<<remote>f:\code\Auto.js\test>:7)

我测试发现，把参数 region 的范围改小了，就没有这个问题了。但是现在的这个数值也没有超出屏幕分辨率，我测试的手机是1280*720分辨率的。 
安卓版本：7.0
Auto.js版本：3.0和3.1和4.0.4Alpha6版本均测试都存在。

代码如下：
//请求截图
if(!requestScreenCapture()){
    toast("请求截图失败");
    exit();
}
var img = captureScreen();
var point = images.findMultiColors(img, "#F0E040", [[-6,0,"#EFE140"],[4,0,"#EEDE38"],[6,0,"#7C5A3D"],[-6,-22,"#7B593D"],[-6,17,"#7B593D"]],{
    threshold:8,
    region:[50,421,700,710]
    //region:[50,421,600,510]
});
console.log(point)

**Comment by nkchwfree** [comment]
region:[50,421,700,710]

**Comment by hyb1996** [comment]
Auto.js版本是多少

**Comment by nkchwfree** [comment]
目前我用的是3.1.0 Beta版本，3.1版本和4.0.4Alpha6版本我也试过，也有同样的问题。

**Comment by hyb1996** [comment]
@nkchwfree 问题已经不存在了吗
