### ISSUE TITLE
支持应用内Webview点击吗，比如支付宝蚂蚁森林等

### ISSUE THREAD

**Issue by jp1017** [hyb1996/Auto.js#405]

**Comment by jp1017** [comment]
貌似仅支持chrome？https://github.com/hyb1996/Auto.js/issues/254

**Comment by hyb1996** [comment]
支付使用内置浏览器，虽然能获取位置，不知道能不能确定。
这个取决于浏览器的支持。
看看一些浏览器的设置有没有开启无障碍选项
