### ISSUE TITLE
请问使用 click 时，必须要先 sleep 一段时间才点击成功是什么原因？

### ISSUE THREAD

**Issue by Nick-Hopps** [hyb1996/Auto.js#408]
![qq 20181125194208](https://user-images.githubusercontent.com/16911282/48978697-76be5a00-f0ea-11e8-8d7e-1884dcbd75df.png)

如果不加 sleep，click 的返回结果是 true，但是实际并没有点击。sleep 经测试 20ms 左右即可。

**Comment by hyb1996** [comment]
对话框需要一定时间消失吧，一般一帧是16ms

**Comment by Nick-Hopps** [comment]
好的，谢谢
