### ISSUE TITLE
打包好的应用运行出现 Cannot find function waitFor in Object

### ISSUE THREAD

**Issue by veryyoung** [hyb1996/Auto.js#412]
![image](https://user-images.githubusercontent.com/5799652/49493622-c09c0280-f897-11e8-9783-0093c8af5f87.png)

我在最开头加了句 auto.waitFor()
在部分机型上好使，在红米5Plus Android 7.1.2机型上出现如上错误，请问作者这是什么情况，应该如何解决啊？
谢谢

**Comment by hyb1996** [comment]
打包插件不对应。
