### ISSUE TITLE
bugs: system stopped working after start accessibility service

### ISSUE THREAD

**Issue by Sodium-Aluminate** [hyb1996/Auto.js#416]
在试图使用root(Magisk 18.0)开启无障碍时发生错误，然后跳转到手动授权，授权后点击屏幕任何位置（包括虚拟按键）都无反应（但返回键有震动反馈），物理按键（电源键）依旧可以关闭屏幕。
在重启后autojs直接获得了无障碍权限。

事件出现了2次（分别在新旧两个不同包名的版本上），尚未刻意尝试再复现。

**Comment by Sodium-Aluminate** [comment]
已复现，另外，当不使用root开启无障碍时无此问题。

**Comment by Sodium-Aluminate** [comment]
设备版本：android8.1 (aex5.8)
（我认为很有可能和这有关）

**Comment by Sodium-Aluminate** [comment]
在获得无障碍权限后，只要关闭该权限（无论是在系统设置内还是程序内），下次启用时就会发生此问题

**Comment by Sodium-Aluminate** [comment]
额外发现的特性：当开发者模式下的“指针位置”和“点按操作反馈”同时开启后，再次复现这个bug的结果：
![screenshot](https://user-images.githubusercontent.com/38349409/49798579-9194fd80-fd7d-11e8-993b-be3ff1b9cbc8.png)

指针位置没有识别，但是点按操作反馈却有反应了？？？

**Comment by Sodium-Aluminate** [comment]
回滚到3.1.0后问题解决。

**Comment by hyb1996** [comment]
设备型号是什么

**Comment by Sodium-Aluminate** [comment]
是 mido（小米 红米 note 4x）

**Comment by Sodium-Aluminate** [comment]
系统包：
https://downloads.aospextended.com/download/mido/oreo/AospExtended-v5.8-mido-20181107-1819-OFFICIAL.zip
magisk 版本：18.0

**Comment by hyb1996** [comment]
我估计很难调试，毕竟没有note4x，使用测试平台的机器也不可能给他刷个包

**Comment by Sodium-Aluminate** [comment]
可以将logcat或其他获取日志的方法告诉我吗？

**Comment by hyb1996** [comment]
酷安上搜索Logcat，找到98kb的那个很小的应用，安装后打开，授予root权限。
点击start。
复现一次按钮失灵，把sd卡根目录的log.txt发送给我（可以直接上传到github或者QQ私聊发送）。
感谢！！

**Comment by hyb1996** [comment]
没问题，即使重启，log.txt也会保存的。
如果有adb，则直接执行`adb shell logcat -f /sdcard/autojs_log.txt`，
然后复现一次bug，之后发送autojs_log.txt文件即可（重启该文件也会保留）。

**Comment by hyb1996** [comment]
另外，不想重启的话，用`adb pull /sdcard/autojs_log.txt`可以把文件传输到电脑的当前命令行目录

**Comment by Sodium-Aluminate** [comment]
OK，稍等。

**Comment by Sodium-Aluminate** [comment]
可以提供你的邮箱吗？

**Comment by hyb1996** [comment]
hybbbb1996@gmail.com

**Comment by Sodium-Aluminate** [comment]
已发，请检查“垃圾邮件”。

**Comment by hyb1996** [comment]
收到，感谢 #

**Comment by Sodium-Aluminate** [comment]
应该是我谢谢你才对～(^^♪

**Comment by hyb1996** [comment]
从这个日志里面没有看到任何异常的地方，开启服务后服务仍然在后台正常运行，并且AccessibilityEvent也始终在记录着，系统也没有报错。
你加一下内测群看看最新版还会不会。QQ群：586823180

**Comment by Sodium-Aluminate** [comment]
申请了，请接受。

**Comment by ChromesRam** [comment]
该问题再次出现，程序版本为4.1.0。

**Comment by Sodium-Aluminate** [comment]
再次出现，程序版本为4.1.0，正在尝试更新到4.1.1alpha。

**Comment by Sodium-Aluminate** [comment]
在程序更新的瞬间，"_指针位置没有识别，但是点按操作反馈却有反应_"，"_点击屏幕任何位置（包括虚拟按键）都无反应（但返回键有震动反馈），物理按键（电源键）依旧可以关闭屏幕。_"的情况也会出现。

**Comment by hyb1996** [comment]
“程序更新的瞬间”系统会强制杀死Auto.js进程，我觉得这个是导致按键失灵的原因，系统应该背锅，没有做好强制停止程序时也关闭无障碍连接的事情。

**Comment by Sodium-Aluminate** [comment]
正在试图向AEX甩锅（

**Comment by thinkwithlinc** [comment]
同复现这个问题，表现情况，屏幕点击无响应，但可以响应实体按键，只能按住电源强行重启
android 8.1 / android 7.1 
autojs版本 4.0.5Alpha
复现过程，100%必复现
场景1：
1.打开autojs，打开无障碍服务，无任何问题；然后在autojs界面中关闭无障碍，退出autojs
2.重新打开autojs，打开无障碍服务，直接无响应
场景2：
1.打开autojs，打开无障碍服务
2.不退出autojs，关闭无障碍服务，重新打开无障碍服务，直接无响应

不知道是否有版本解决了这个问题

**Comment by Sodium-Aluminate** [comment]
俺也一样！（同样的复现方式）
拿fooview的无障碍测试了该场景，也没有问题。
另外你的复现描述很详细诶…

**Comment by Sodium-Aluminate** [comment]
> 同复现这个问题，表现情况，屏幕点击无响应，但可以响应实体按键，只能按住电源强行重启
> android 8.1 / android 7.1 (root 非root均有测试)
> autojs版本 4.0.5Alpha
> 复现过程，100%必复现
> 场景1：
> 1.打开autojs，打开无障碍服务，无任何问题；然后在autojs界面中关闭无障碍，退出autojs
> 2.重新打开autojs，打开无障碍服务，直接无响应
> 场景2：
> 1.打开autojs，打开无障碍服务
> 2.不退出autojs，关闭无障碍服务，重新打开无障碍服务，直接无响应
> 
> 不知道是否有版本解决了这个问题
> 
> 补充一下，拿coolapk的自动免安装测试了以上场景，没有发现问题

可以给一下系统版本和手机型号吗？便于确定要不要向AEX甩锅

**Comment by thinkwithlinc** [comment]
@Sodium-Aluminate 不倾向是系统问题，因为我拿酷安测试过了，无问题
系统是android8.1 aospextend 红米4
之前是7.1这两天捣鼓了下

**Comment by Sodium-Aluminate** [comment]
> @Sodium-Aluminate 不倾向是系统问题，因为我拿酷安测试过了，无问题
> 系统是android8.1 aospextend 红米4
> 之前是7.1这两天捣鼓了下
> 有个细微的区别是酷安关闭无障碍会跳到系统设置让用户手动关闭
> 之前测试过，无响应的一瞬间autojs其实还在运行的，连了adb shell，看了还有进程
> 
> 重启后，autojs显示无障碍是服务是打开的，也能点进去关闭

我觉得还是AEX的锅…

**Comment by thinkwithlinc** [comment]
看到外面有个issue也是一样的情况
查了一些无障碍的资料，还有源码
https://juejin.im/post/5b27bfc56fb9a00e373bd232
https://github.com/AospExtended/platform_frameworks_base/blob/8.1.x/core/java/android/accessibilityservice/AccessibilityService.java

不知道其他机器非aospextend 是否有这个问题

**Comment by hyb1996** [comment]
我试试刷一个aex测试一下
