### ISSUE TITLE
[bug]4.1.0 alpha3版,打包后的脚本,不能正常使用app.startActivity("settings");

### ISSUE THREAD

**Issue by xiaofeng930415** [hyb1996/Auto.js#421]
如题:4.1.0 alpha3版,打包后的脚本,不能正常使用app.startActivity("settings");
其他情况:
1 app.startActivity("console");正常
2 使用平台: 安卓5.1(模拟器与红米3)

有个疑问,就是每次版本更新后,基本上前版本的问题都会得到修复,但出现不少之前一直好好的代码出问题的情况.导致很多不便,作者要忙于修复,脚本作者忙于填坑.希望这个情况能够改善,谢谢.

**Comment by hyb1996** [comment]
已修复
