### ISSUE TITLE
BUG：模块功能 无法正常工作

### ISSUE THREAD

**Issue by Sodium-Aluminate** [hyb1996/Auto.js#422]
完全照抄文档内内容后执行，结果如下：
        03:24:17.362/E: syntax error (file:/storage/emulated/0/脚本/circle.js#3)
	at script(<init>:105)
	at script(<foo>:1)

**Comment by XeroAlpha** [comment]
把 `a ** b` 替换为 `Math.pow(a, b)` 即可，Auto.js不支持 `**` 幂运算符，文档上是错的

**Comment by Sodium-Aluminate** [comment]
即使我删除了式子并改为常数，依旧无效。

10:30:11.803/E: TypeError: TypeError: redeclaration of const circle. (file:///android_asset/modules/jvm-npm.js#60)
TypeError: TypeError: redeclaration of const circle.
    at _load (file:///android_asset/modules/jvm-npm.js:60:0)
    at /storage/emulated/0/脚本/foo.js:1:0

**Comment by hyb1996** [comment]
什么版本的Auto.js

**Comment by Sodium-Aluminate** [comment]
你让我下的那个版本（4.1.0 Alpha3）和上古版本都试过，同样的报错。
