### ISSUE TITLE
问下项目源码 中的一个问题

### ISSUE THREAD

**Issue by fanmingyi** [hyb1996/Auto.js#423]
module.exports 这个语法是nodejs的吧？ 不知道作者在源码哪里加上的，能否指点下。还有就是作者在停止脚本的 悬浮窗没有关闭。还有runtime 部分对象存在内容泄漏 。不妨可以用MAT工具看下

**Comment by hyb1996** [comment]
模块本身是Rhino支持的，另外为了能引用nodejs的模块，还做了一些工作：
[jvm-npm.js](https://github.com/hyb1996/Auto.js/blob/dev/autojs/src/main/assets/modules/jvm-npm.js)
[RhinoJavaScriptEngine](https://github.com/hyb1996/Auto.js/blob/dev/autojs/src/main/java/com/stardust/autojs/engine/RhinoJavaScriptEngine.kt#L118)
