### ISSUE TITLE
4.1.0Alpha5 打包后 sleep() 会阻塞threads.start()启动的线程

### ISSUE THREAD

**Issue by shipengqi** [hyb1996/Auto.js#433]

**Comment by shipengqi** [comment]
```js
    threads.start(function() {
        try {
                toastLog("Start");
                sleep(1000);
                toast("end");
            }
            toastLog("应用列表阅读完成");
        } catch(e) {
            console.error(e);
        }
    });
```

上面的`end`永远不会打印，正常应该阻塞1秒钟，然后打印`end`。

**Comment by hyb1996** [comment]
没有复现该问题

**Comment by a471640241** [comment]
> ```js
>     threads.start(function() {
>             toastLog("Start");
>             sleep(1000);
>             toastLog("end");
>     });
> ```
> 
> 上面的`end`永远不会打印，正常应该阻塞1秒钟，然后打印`end`。

请问你解决了这个问题了吗,我这里也遇到了,sleep() 休眠后直接导致子线程不执行了 系统是MIUI 10稳定版

**Comment by a471640241** [comment]
> ```js
>     threads.start(function() {
>             toastLog("Start");
>             sleep(1000);
>             toastLog("end");
>     });
> ```
> 
> 上面的`end`永远不会打印，正常应该阻塞1秒钟，然后打印`end`。

@shipengqi  请问你解决了这个问题了吗, 我也遇到这个问题了, 在子线程里sleep 直接导致子线程阻塞了 后面的代码都不会执行   系统是MIUI 10稳定版

**Comment by a471640241** [comment]
我发现我是执行了启动 auto.js 之后 sleep就阻塞了

**Comment by shipengqi** [comment]
@a471640241 我改用了`engines.execScriptFile()`去执行子线程的脚本

**Comment by githubchl** [comment]
我也遇到过这个问题，后来发现是autojs的版本和打包工具的版本不一致导致的。我将autojs的版本和打包工具换成4.1.1的就可以了。
