### ISSUE TITLE
runtime.loadJar 问题

### ISSUE THREAD

**Issue by lepon** [hyb1996/Auto.js#434]
runtime.loadJar('****.jar')

然后就会报下面的错误

 java.lang.RuntimeException: Translation has been interrupted

**Comment by suiang** [comment]
@lepon 同一目录下也要写'./*.jar'

**Comment by lepon** [comment]
> runtime.loadJar('/sdcard/jsoup.jar')

不是路径的问题，是因为jar包的问题，eclipse打的不行（估计是打包方式不对），android studio打的包可以

**Comment by lepon** [comment]
> @lepon 同一目录下也要写'./*.jar'

不是路径的问题，是因为jar包的问题，eclipse打的不行（估计是打包方式不对），android studio打的包可以

**Comment by yhuaqiang** [comment]
而且,loadjar 重复执行的话,会异常.
就是这个脚本执行第二次就不行了.必须把这行Loadjar注释掉

**Comment by hyb1996** [comment]
在pro 8.6已修复
