### ISSUE TITLE
bug app.viewFile和app.editFile异常

### ISSUE THREAD

**Issue by xiaofeng930415** [hyb1996/Auto.js#436]
4.1.0 alpha5版

界面进入文件，edit
es文件管理器，无法保存成功
office mobile版 会以只读模式打开
wps 会另外生成临时文件存储

![image](https://user-images.githubusercontent.com/34148523/50755423-e865f800-1293-11e9-86d0-4b3bc1db8a91.png)
原始路径是微信下载位置

如果所有文件管理器都不奏效，应该是autojs bug吧

**Comment by XeroAlpha** [comment]
我感觉适配不好的原因还是因为无法获取文件路径
结果什么最近文件之类的也不好做，如果编辑的时候aj挂了恐怕还保存不了。
例如:
```
java.lang.SecurityException: Permission Denial: opening provider org.autojs.autojs.external.fileprovider.AppFileProvider from ProcessRecord{7e32ae2 32223:com.rhmsoft.edit/u0a155} (pid=32223, uid=10155) that is not exported from UID 10170
```

**Comment by xiaofeng930415** [comment]
@hyb1996 谢谢回复，感觉应该是这个问题吧，华为8.0
