### ISSUE TITLE
4.1.0Alpha5 loopTimes 无效，脚本只会运行一次

### ISSUE THREAD

**Issue by shipengqi** [hyb1996/Auto.js#439]
代码如下：
```js
engines.execScriptFile("./appScripts.js", {loopTimes: 0});
```

`appScripts.js`运行一次之后，就停止了，没有循环运行。

**Comment by snailuncle** [comment]
如果你现在想无限循环,可以这样设置
se=engines.execScriptFile("./appScripts.js", {loopTimes: 0.1});
log(se.getConfig())

loopTimes: 0.1

**Comment by shipengqi** [comment]
@snailuncle 好的，谢谢。而且我试了一下，只要`loopTimes`不为`0`，是可以循环运行的。

**Comment by hyb1996** [comment]
确实是Bug，感谢反馈
