### ISSUE TITLE
4.1.0Alpha5 events.broadcast: 脚本间广播，事件监听回调没有触发

### ISSUE THREAD

**Issue by shipengqi** [hyb1996/Auto.js#440]
**`test1.js`**：
```js
var e = engines.execScriptFile(files.cwd() + "/test2.js", {loopTimes: 0});
sleep(2000);
events.broadcast.on("hello", function(name) {
  console.log("Hello, " + name);
});

// 保持脚本运行
setInterval(() => {}, 1000);
```

**`test2.js`**：
```js
console.log('test broadcast---------------------');
// 向该脚本发送事件
events.broadcast.emit("hello", "xiaoming");
```

**期望**：
无效循环输出：
```bash
test broadcast---------------------
Hello, xiaoming
test broadcast---------------------
Hello, xiaoming
test broadcast---------------------
Hello, xiaoming
...
```
**实际**：
脚本日志只输出了一次`test broadcast---------------------`。

**问题**：
1. `events.broadcast.on`监听的`hello`事件回调没有执行。
2. `{loopTimes: 0}`的无限循环设置没有效果。

**Comment by snailuncle** [comment]
events.broadcast.emit是一次性的.
运行完就没了,

要先监听广播,再发送广播,

test1中sleep(2000)的时候,广播已经发送完了,
但监听还没有开始

要不你把监听放脚本最前面?

先监听,后发送广播.

我这样理解对不对?

**Comment by shipengqi** [comment]
@snailuncle 这个问题和先后关系不大，因为我配置`{loopTimes: 0}`循环运行，所以就算第一次没有监听到`hello`事件，后面也会监听到。这个问题是因为配置`{loopTimes: 0}`无效。
