### ISSUE TITLE
4.1.0Alpha5 打包后 currentPackage() 获取不到当前运行应用的包名

### ISSUE THREAD

**Issue by shipengqi** [hyb1996/Auto.js#442]
`test.js`：
```js
console.log('-------------------' + currentPackage());
```
`main.js`：
```js
engines.execScriptFile(files.cwd() + "/test.js");
```

现象：
打包后通过`engines.execScriptFile`运行`test.js`，打印结果为`-------------------`，`currentPackage()`获取的为空字符串。

脚本引擎运行脚本是不是获取不到当前应用的包名？

**Comment by JustForSmiling** [comment]
请问这个问题解决了吗    我用的是8.0的autojsPro，也遇到了这个问题，为什么没有看到回复就关掉了这个issue呀

**Comment by hyb1996** [comment]
> 请问这个问题解决了吗 我用的是8.0的autojsPro，也遇到了这个问题，为什么没有看到回复就关掉了这个issue呀

可以用auto.setFlags()方法用不同方式获取currentPackage

**Comment by JustForSmiling** [comment]
好的，非常感谢，我试一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月24日(星期五) 中午1:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hyb1996/Auto.js] 4.1.0Alpha5 打包后 currentPackage() 获取不到当前运行应用的包名 (#442)





  
请问这个问题解决了吗 我用的是8.0的autojsPro，也遇到了这个问题，为什么没有看到回复就关掉了这个issue呀
  
可以用auto.setFlags()方法用不同方式获取currentPackage
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
