### ISSUE TITLE
4.1.0Alpha5 关于 UiSelector.id(resId)

### ISSUE THREAD

**Issue by shipengqi** [hyb1996/Auto.js#443]
`UiSelector.id(resId)`这个方法，可以为当前选择器附加"id等于resId"的筛选条件。

这里的`resId`必须是以"包名:id/"开头，否则会自动添加"包名:id/"为开头，但是我现在碰到了控件id并不是
以"包名:id/"开头的，例如`btn_more_details`，如果直接使用`id('btn_more_details').findOne()`是找不到这个控件的，我只能用`idContains('btn_more_details').findOne()`来找到这个控件，但其实`btn_more_details`
就是完整的控件id。

是不是可以提供一个不自动补全id的方法？

**Comment by hyb1996** [comment]
写全名。例如：
```
id('android:id/btn_more_details').findOne()
```

**Comment by shipengqi** [comment]
@hyb1996 我通过`console.log(text('查看全文').fineOne())`，查看日志，发现id的全名就是`btn_more_details`，其他大部分id都带有`包名:id/`，比如`com.jinfen.qukan:id/iv_close`。
