### ISSUE TITLE
4.1.0Alpha5 打包后，每次打开应用，ui脚本都会重新加载运行

### ISSUE THREAD

**Issue by shipengqi** [hyb1996/Auto.js#445]

**Comment by BelongsH** [comment]
我也发现了这个问题。

每次点home键,ui脚本会重新加载。

将ScriptExecuteActivity>FLAG_ACTIVITY_NEW_TASK注释后不会出现。但是9.0以上运行不了

**Comment by hyb1996** [comment]
已修复。
https://github.com/hyb1996/Auto.js/commit/a0e9dbcc2e06791239cae54debb6dfe1c313e09b
