### ISSUE TITLE
使用Android Studio3.3版本build的时候报错ezy.assist.compat不存在，但是添加implementation 'com.github.czy1121:settingscompat:1.1.4'又提示Program type already present

### ISSUE THREAD

**Issue by zhaozhongyu** [hyb1996/Auto.js#449]
使用Android Studio3.3版本，并且因此更改了targetSdkVersion到27，然后build的时候报错ezy.assist.compat不存在，但是添加implementation 'com.github.czy1121:settingscompat:1.1.4'又提示Program type already present

**Comment by hyb1996** [comment]
切换到dev分支

**Comment by bosslichuan** [comment]
是不是文件编码问题哦




| |
李川
邮箱：330394383@163.com
|

签名由 网易邮箱大师 定制

在2019年04月11日 17:40，William.Forever 写道：

Closed #449.

**Comment by hVenus** [comment]
添加，implementation 'com.github.hyb1996:settingscompat:1.1.5'
作者在com.github.czy1121:settingscompat:1.1.4的基础上做了修改，在common中添加了修改过的的依赖，所以会报Program type already present.
