### ISSUE TITLE
希望增加可动态申请的权限选项等5个问题~等

### ISSUE THREAD

**Issue by xiaofeng930415** [hyb1996/Auto.js#451]
![image](https://user-images.githubusercontent.com/34148523/51828650-ffde5100-2326-11e9-9d7c-3abe37075d4f.png)
1 希望增加可动态申请的权限选项
2 如何通过APK编辑器来增加Auto.js以及Auto.js打包的应用的权限？可否大概介绍一下。
是否都需要增加应用权限显式声明，还是可以只在runtime.requestPermissions(["access_fine_location"]);增加其他权限项即可
3 群里之前有全权限版，是否能放一个全权限版的最新版。
4 我需要的是通讯录权限，是否考虑可以放开更多权限。
5 个人建议：按键精灵有很多第三方插件，提供了很多官方没有的功能， @hyb1996 是否考虑下让其他作者来完善插件生态。

**Comment by hyb1996** [comment]
template.apk是inrt模块编译出来的apk

**Comment by hyb1996** [comment]
Auto.js Pro可能会支持全权限

**Comment by baiqb** [comment]
> Auto.js Pro可能会支持全权限

Pro要在哪里面买呢，想买都找不到地方呢~
@hyb1996
