### ISSUE TITLE
bug: nodeinfo.viewIdResourceName must not be null

### ISSUE THREAD

**Issue by qinst64** [hyb1996/Auto.js#463]
新版本4.0.5Alpha只要使用id("com.android.systemui:id/xxx...")的时候会报错
```
错误:Wrapped java.Iang.IllegalStateException:  nodelnfo. viewldResourceName must  not be null
```
4.0.4Alpha6 无此问题

生成代码功能用的时候也基本会奔溃, 因已降级忘了看log, 好像也是这个错

**Comment by zhizunbao84** [comment]
这个我也碰到了

**Comment by xiaohe8** [comment]
我也出现这个错误

错误:Wrapped java.Iang.IllegalStateException:  nodelnfo. viewldResourceName must  not be null
