### ISSUE TITLE
 锁屏KeyCode("KEYCODE_POWER");不起作用

### ISSUE THREAD

**Issue by ForgetSky** [hyb1996/Auto.js#464]

**Comment by seamen** [comment]
遇到同样的问题，不知道是不是需要Root才行

**Comment by nckf** [comment]
参考资料：[AutoJs-Docs](https://hyb1996.github.io/AutoJs-Docs/#/keys?id=keycodecode)
>按键模拟部分提供了一些模拟物理按键的全局函数，包括Home、音量键、照相键等，有的函数依赖于无障碍服务，有的函数依赖于root权限。

>一般来说，以大写字母开头的函数都依赖于root权限。执行此类函数时，如果没有root权限，则函数执行后没有效果，并会在控制台输出一个警告。

**Comment by nckf** [comment]
>依赖 Root 权限
```
Power()
模拟按下电源键。 此函数依赖于root权限。
```
> 部分依赖 Root 权限
```
KeyCode(code)
```

> 他们是需要的权限以及效果都是一样的
```
Power();
KeyCode("KEYCODE_POWER");
KeyCode("26");
```
