### ISSUE TITLE
关于 setScreenMetrics() 设置屏幕分辨率

### ISSUE THREAD

**Issue by shipengqi** [hyb1996/Auto.js#466]
如果使用`setScreenMetrics`设置屏幕分辨率，那么下面的代码：
```js
//获取这个控件
var widget = id("xxx").findOne();
//获取其中心位置并点击
click(widget.bounds().centerX(), widget.bounds().centerY());
```

`widget.bounds().centerX()`,和`widget.bounds().centerY()`获取到的是控件准确的位置，自动缩放了以后，还能点击到正确的位置么？

**Comment by hyb1996** [comment]
不能

**Comment by shipengqi** [comment]
@hyb1996 谢谢，我觉得`click`，`press`函数可以加一个参数，让用户决定是否需要自动缩放。
