### ISSUE TITLE
在DFS.KT val parent = stack.pop() 怎么有可能会返回NULL

### ISSUE THREAD

**Issue by windanan** [hyb1996/Auto.js#484]
`
public class DFS implements SearchAlgorithm {

    @Override
    public ArrayList<UiObject> seach(UiObject root, Filter filter) {
        ArrayList<UiObject> result = new ArrayList<>();
        LinkedList<UiObject> stack = new LinkedList<>();
        stack.push(root);
        while (!stack.isEmpty()) {
            UiObject parent = stack.pop();
            for (int i = parent.childCount() - 1 ; i >= 0 ; i--) {
                if (parent.child(i) == null) continue;
                stack.push(parent.child(i));
            }
            if (filter.isIncluded(parent)) {
                result.add(parent);
                if (result.size() >= Integer.MAX_VALUE) {
                    break;
                }
            } else {
                if (parent != root) parent.recycle();
            }
        }
        return result;
    }
}`

改写成了JAVA..
经测试后发现.偶尔会出现parent为NULL.按理来讲,不应该呀.在PUSH前,分明有判断进行了验证
if (parent.child(i) == null) continue;
断点发现.参数root是不为空的..百思不得其解..
真心谢谢你的解答

**Comment by hyb1996** [comment]
parent.child(i)这类方法是实时获取的，也就是可能第一次调用非空，而第二次调用为空，应该有一个变量存起来。

**Comment by windanan** [comment]
理解了.谢拉
