### ISSUE TITLE
调用home() 方法后，在调用启动app方法，app无法启动。小米Mix3手机。

### ISSUE THREAD

**Issue by lyings** [hyb1996/Auto.js#490]
同上

**Comment by XeroAlpha** [comment]
请不要禁用Auto.js后台弹出界面的权限，你禁用了当然无法启动app了

**Comment by lyings** [comment]
我的手机是MIUI10.3 这个app的所有权限都开了。还是会出现这种情况，比如我写个while循环 调用了home()方法后，在调用LauchApp("QQ")。就不能启动qq.

**Comment by Qiguang** [comment]
这个问题是新手常犯，开启后台弹出界面权限就行了，另外，别升级10.3.1，我升级完，auto.js都打不开了
