### ISSUE TITLE
4.0.1 Beta "canvas" is not defined

### ISSUE THREAD

**Issue by chen-jiawei** [hyb1996/Auto.js#494]
复制文档的例子运行，报错显示"canvas" is not defined
并且另一个报错是《Java class "android.graphics.Paint" has no public instance field or method named "STYLE". 》

var paint = new Paint();
//设置画笔为填充，则绘制出来的图形都是实心的
paint.setStyle(Paint.STYLE.FILL);
//设置画笔颜色为红色
paint.setColor(colors.RED);
//绘制一个从坐标(0, 0)到坐标(100, 100)的正方形
canvas.drawRect(0, 0, 100, 100, paint);

**Comment by XeroAlpha** [comment]
首先这些代码是写在ScriptCanvas的draw事件里的，其次，是Style而不是STYLE

**Comment by chen-jiawei** [comment]
@XeroAlpha 是的哦，我是在JS写的，而且是复制官方文档的示例代码

**Comment by liuyib** [comment]
同问啊，canvas 和 Paint 都是 "is not defined"，官方文档里只说了 API 怎么用，并没说这些变量怎么来。
