### ISSUE TITLE
编译编译报错，透心凉那种

### ISSUE THREAD

**Issue by a309371807** [hyb1996/Auto.js#501]
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app, autojs, automator, common, inrt

WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app, autojs, automator, common, inrt

WARNING: Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
Affected Modules: app, autojs, automator, common, inrt

**Comment by a309371807** [comment]
ERROR: Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:design:25.4.0] AndroidManifest.xml:28:13-35
	is also present at [com.android.support:appcompat-v7:26.1.0] AndroidManifest.xml:28:13-35 value=(26.1.0).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

**Comment by a309371807** [comment]
> Task :app:compileCommonDebugJavaWithJavac
Gradle may disable incremental compilation as the following annotation processors are not incremental: androidannotations-4.3.1.jar (org.androidannotations:androidannotations:4.3.1), butterknife-compiler-8.6.0.jar (com.jakewharton:butterknife-compiler:8.6.0), compiler-4.2.0.jar (com.github.bumptech.glide:compiler:4.2.0), dbflow-processor-4.1.2.jar (com.github.Raizlabs.DBFlow:dbflow-processor:4.1.2).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
错误: Could not find the AndroidManifest.xml file, using  generation folder [D:\MyAndroidStudioProject\Auto.js-master\app\build\generated\source\apt\common\debug])
注: [1] Wrote GeneratedAppGlideModule with: []
警告: 将不对在最后一个循环中创建的类型为 'com.raizlabs.android.dbflow.config.TimedTaskDatabaseTimedTaskDatabase_Database' 的文件进行注释处理。
1 个错误
1 个警告

> Task :app:compileCommonDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileCommonDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 37s
42 actionable tasks: 26 executed, 16 up-to-date

**Comment by cnnix** [comment]
同样的错误,不知道怎么解决

**Comment by landscapeside** [comment]
试试

android{
	defaultConfig{
		javaCompileOptions {
		    annotationProcessorOptions {
		        arguments = [
			        'resourcePackageName': "xxx你的包名",
		            "androidManifestFile": "$projectDir/src/main/AndroidManifest.xml".toString()
		        ]
		    }
		}
	}
}
