### ISSUE TITLE
autojs的实现自动答题，怎么链接数据库或者json？

### ISSUE THREAD

**Issue by Kleverx** [hyb1996/Auto.js#527]
要读取题目然后到本地查找答案，安卓自带的sqlite3在autojs内能用吗，如果不能有其他的数据库吗？json可以用吗？

链接数据库/读写json的代码怎么写呢？

**Comment by suiang** [comment]
JSON不就是为了JavaScript量身定制的咩:dress:

**Comment by Kleverx** [comment]
业余自学的python，对js一窍不通，json搜索过，但是太乱杂，没找到系统的js的json教程。。。。

**Comment by suiang** [comment]
@Kleverx 

```js

//打开控制台
console.show()

var Obj = {
    id: '01',
    name: 'Tom'
};

//序列化方法
var js = JSON.stringify(Obj);
console.log(js)

//反序列化方法
var json = JSON.parse(js)
console.log(json.id)

```

和Python处理JSON一样吧:grinning:

**Comment by lgpersonal** [comment]
可以用sqlite3
示例
        importClass(android.database.sqlite.SQLiteDatabase);

        function sqlQuery() {
            //数据文件名
            var dbName = "data.db";
            //文件路径
            var path = files.path(dbName);
            //确保文件存在
            if (!files.exists(path)) {
                files.createWithDirs(path);
            }
            //创建或打开数据库
            var db = SQLiteDatabase.openOrCreateDatabase(path, null);
            var _timu = 'Question here';
            var sqlstr="SELECT answer FROM tiku WHERE question LIKE '%"+_timu+"%'";
            toastLog(sqlstr);

            var cursor=db.rawQuery(sqlstr,null);
            toastLog("共有"+cursor.getCount()+"条记录");
            if(cursor.getCount()){
                cursor.moveToFirst();
                do{
                    toastLog(cursor.getString(0));
                }while(cursor.moveToNext());
            }
            cursor.close();
            db.close();
        }
