### ISSUE TITLE
该如何编译安装

### ISSUE THREAD

**Issue by ninjachen** [hyb1996/Auto.js#529]
Hello，我下了这个源码，然后切到了dev分支，出来的界面和别人截图里的不一样，请问该怎么编译出release的样子？

我也看了readme，好像都是使用手册，没有介绍编译这一块的内容
ps：想编译是因为首页给的下载链接不能用了。

![image](https://user-images.githubusercontent.com/3176871/64919309-c8e87d00-d7db-11e9-8ab7-7151061e4508.png)

**Comment by hyb1996** [comment]
右上角将模块inrt切换为app即可
