### ISSUE TITLE
notification.delete(); 执行失败

### ISSUE THREAD

**Issue by zhaohuiyingxue** [hyb1996/Auto.js#531]
var qnames=new Array('优惠','机电');
var keyword="***";

auto();
events.observeNotification();
events.onNotification(function(notification) {
    FiterNotification(notification);
});

function FiterNotification(notification) {
    //非指定群退出
    if(notification.getPackageName()!="com.tencent.mm")return;
    if(qnames.indexOf(notification.title)==-1)return;
    
    log("群名: " + notification.title);
    log("内容: " + notification.text);
    if(notification.text.indexOf(keyword) != -1){
        log("打开");
        toast(notification.text);
        notification.click();
        GetCard();
    }else{
        setTimeout(function(){
            try {
                log("删除");
                notification.delete();
                log("删除成功");
            } catch (error) {log("删除失败"+error+notification);}
        }, 1000);
    }
    log("=============");
}
function GetCard(){

}

以上代码，出现错误如下：
15:44:18.219/D: **删除失败JavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.PendingIntent.send()' on a null object reference**Notification{packageName='com.tencent.mm', title='淘宝京东拼多多优惠群, text='[54条]一尘: 还差一个一个'} 

是我用的不对么？应该怎么用才行呢？把notification打印出来也不是空的。
另外，通知监听感觉挺耗费资源的。。。

**Comment by hyb1996** [comment]
Pro已修复
