### ISSUE TITLE
4.3.1版本打包后进入应用会闪退

### ISSUE THREAD

**Issue by wshx21** [hyb1996/Auto.js#535]
4.3.1版本打包后进入应用会闪退：
debug 无问题 release 会闪退

**Comment by zzliux** [comment]
最高好像是4.1.1alpha吧

**Comment by hyb1996** [comment]
楼上说得对

**Comment by hike2008** [comment]
最新版本的代码确实打release包会崩溃

**Comment by Gxz-NGU** [comment]
我copy了一份在github私有库，按照作者的actions的Android CI方式，用自己的签名文件生成app-common-armeabi-v7a-release.apk，但是这个apk安装好之后，进入就闪退。

**Comment by Gxz-NGU** [comment]
> 我copy了一份在github私有库，按照作者的actions的Android CI方式，用自己的签名文件生成app-common-armeabi-v7a-release.apk，但是这个apk安装好之后，进入就闪退。

进入android studio之后，不要更新gradle的插件，一切的改动都用git revert掉，然后就成功了
