### ISSUE TITLE
4.1.1Alpha2版本无法模拟点击图片

### ISSUE THREAD

**Issue by williamnie** [hyb1996/Auto.js#542]
您好，我在按照文档中的介绍，模拟点击微信朋友圈的相机图标，一直无法点击，是做了限制，还是我写的代码不对呢？
auto.js版本：4.1.1Alpha2
我的代码：

```
1.className("android.support.v7.widget.LinearLayoutCompat").depth(8).findOne().click()
2.click(929, 82, 1080, 212)
```
这两种都不行，第一种是通过布局查询生成的代码，第二种的坐标是按照文档中介绍的，通过布局查询查到的。
不知道是做了安全限制，还是我的代码不对，刚开始学习auto.js，希望能解答下。十分谢谢！

**Comment by hyb1996** [comment]
4.1.1版本是没有做限制的，具体可以再看看为什么没有生效

**Comment by williamnie** [comment]
> 4.1.1版本是没有做限制的，具体可以再看看为什么没有生效

我测试了锤子 R1，安卓版本8.1.0，和一加3，安卓版本9，微信版本均为7.0.8，都是无法点击
