### ISSUE TITLE
Documentation in English

### ISSUE THREAD

**Issue by manikantag** [hyb1996/Auto.js#544]
Hi, is there any chance of getting English documentation? Google Translated wording is only making partial sense.

**Comment by yingshaoxo** [comment]
I'm working on it: https://github.com/yingshaoxo/Auto.js

**Comment by hyb1996** [comment]
We now provide the English version of the App and documentation, although it is a bit late.
[Auto.js Pro on Google Play](https://play.google.com/store/apps/details?id=org.autojs.autojspro)
[Documentation in English](https://g.pro.autojs.org/docs/#/)
