### ISSUE TITLE
发现bug

### ISSUE THREAD

**Issue by primejava** [hyb1996/Auto.js#545]
`auto.waitFor();

descs=className("android.view.View").depth(14).descEndsWith("想要").find().forEach(child => {
var target = child.parent().parent();
target.click();
sleep(2000);
back();
});`

下面的child元素遍历的时候,只有第一个child的parent不为null,其他的全部报空指针错误
child.parent().parent();

**Comment by hyb1996** [comment]
需要重新find一下
