### ISSUE TITLE
Where to get the APK?

### ISSUE THREAD

**Issue by IzzySoft** [hyb1996/Auto.js#546]
Would you consider making the APK available again (preferably attacht to its corresponding release)? Currently, the link from the readme leads to an empty page.

**Comment by surgor** [comment]
这个提问 https://github.com/hyb1996/Auto.js/issues/500 里面有其他人分享的下载链接

**Comment by IzzySoft** [comment]
I don't speak Chinese, sorry (but hopefully got the idea, thanks). I was asking whether the APK could be made available here at Github, e.g. by [tagging releases](https://github.com/hyb1996/Auto.js/releases) and attaching the APK. Makes them much easier to find.

**Comment by testerwang11** [comment]
downloadurl:https://www.lanzous.com/b895913/
password:abo3

Maybe the national conditions, you know...

**Comment by IzzySoft** [comment]
Thanks, but that won't work for me. Reason I'm asking is [your app in my repo](https://apt.izzysoft.de/fdroid/index/apk/org.autojs.autojs). My updater script can deal fine with APKs attached to releases or even inside the repo – but not with password protected sites.

**Comment by hyb1996** [comment]
Apk is now avaible as artifacts of [Github CI](https://github.com/hyb1996/Auto.js/commit/8cab65ee1d5237b971ad9d9cc739a57326620847/checks?check_suite_id=336448810)

**Comment by IzzySoft** [comment]
Thanks @hyb1996 – unfortunately, my updater doesn't know how to deal with that either. It can work with

* APKs attached to their corresponding release
* APKs inside the repo structures
* APKs provided via "fixed URLs" (i.e. same URL always pointing to the latest APK) where the server provides a LAST_MODIFIED header field

Apart from that, for the repo the APK would need to be signed.

**Comment by mumuyizhou** [comment]
> Thanks @hyb1996 – unfortunately, my updater doesn't know how to deal with that either. It can work with
> 
> * APKs attached to their corresponding release
> * APKs inside the repo structures
> * APKs provided via "fixed URLs" (i.e. same URL always pointing to the latest APK) where the server provides a LAST_MODIFIED header field
> 
> Apart from that, for the repo the APK would need to be signed.

https://github.com/Ericwyn/Auto.js/releases
https://www.lanzous.com/i6xeadg
https://cnm.cool/autojs/
Try links above?

**Comment by IzzySoft** [comment]
Thanks! But:

* The first is a different repo – how is the fork related? Is it a different app based on this, is it maintained and kept in sync?
* Second link doesn't resolve for me (server not found)
* 3rd is a web page wich contains a link to an APK (i.e. doesn't match any of the criteria I've just mentioned).

**Comment by lesca** [comment]
> Thanks! But:
> 
> * The first is a different repo – how is the fork related? Is it a different app based on this, is it maintained and kept in sync?
> * Second link doesn't resolve for me (server not found)
> * 3rd is a web page wich contains a link to an APK (i.e. doesn't match any of the criteria I've just mentioned).

The owner is wipping the repository, removing the open source version of apk from the store, as there are some abuse cases in China. 

Not only for you, but all normal users who properly using the app is facing the same issue - nowhere to find the offical apk.

Thus, we have to resort to those mirrors, or just complie your own.

From my finding, the author wont maintain the open source version any more. New "pro" versions will appeal but with lots of limitations.

**Comment by IzzySoft** [comment]
Thanks for the explanation, @lesca!

**Comment by mo-han** [comment]
@IzzySoft 
Your software repo is terrific.
Thank you for all the work and time behind it.
