### ISSUE TITLE
runtime.loadJar 缓存咨询

### ISSUE THREAD

**Issue by marvel00000** [hyb1996/Auto.js#549]
场景描述：
1.runtime.loadJar加载jar包，然后import
2. 更新jar包内容，然后重新放置到手机上
3.调用jar包的方法获取的结果还是之前jar包的，感觉jar包加载为dex文件时有缓存，并不能实时加载jar

**Comment by hyb1996** [comment]
在开源版是有这个问题的，可以用runtime.unloadJar卸载某个jar以及他的缓存。（不记得开源版有没有这个函数）

**Comment by RayMMond** [comment]
@hyb1996  通过`runtime.loadJar'加载JAR之后，关闭APP重新运行 会报 
```
Wrapped com.stardust.pio.UncheckedIOException：java.io.FileNotFoundException：/data/user/0/org.autojs.autojs/cache/classes/xxxxxx.....xxxx.dex
```
在pro版本里面使用 `unloadJar` 也不行，但是清理APP所有数据（包括登录等数据）之后恢复正常
然后在jar同级目录下会生成oat的文件夹，里面会有个 xx.jar.cur.prof 的空文件
