### ISSUE TITLE
不支持ES6的``拼接字符串吗？

### ISSUE THREAD

**Issue by shanlanCoding** [hyb1996/Auto.js#550]
代码如下：
![image](https://user-images.githubusercontent.com/44717382/69548990-64b01980-0fd3-11ea-99f7-58b852358178.png)

报错如下：
![image](https://user-images.githubusercontent.com/44717382/69548958-52ce7680-0fd3-11ea-98b1-f0ea6ac54a10.png)

**Comment by hyb1996** [comment]
Rhino支持的ES标准比较低，欢迎等待基于Node.js的Pluto.js

**Comment by shanlanCoding** [comment]
> Rhino支持的ES标准比较低，欢迎等待基于Node.js的Pluto.js

Pluto.js不支持无障碍吧？我写脚本是为了完成自己个人需求。

**Comment by hyb1996** [comment]
建议用webpack打包为es5运行

**Comment by hyb1996** [comment]
https://github.com/snailuncle/webpackBaleAutojs

**Comment by shanlanCoding** [comment]
> 建议用webpack打包为es5运行

好的，没事，影响不大，低等级的ES也能写。谢谢你耐心解答。

**Comment by hyb1996** [comment]
现已在Pro 8.6中支持Node.js
