### ISSUE TITLE
编译运行提示找不到符号BuildActivity_

### ISSUE THREAD

**Issue by huoxiangdong** [hyb1996/Auto.js#556]
![截屏2019-12-15上午11 41 17](https://user-images.githubusercontent.com/18095882/70857786-fe624b00-1f2f-11ea-8176-2ed76f8c6c95.png)
请教，运行提示找不到符号，怎么解决

**Comment by nckf** [comment]
Android编程不熟悉，我前阵子也编译过，遇到过这样的问题，记得是各种依赖更新就可以了。

**Comment by huoxiangdong** [comment]
> Android编程不熟悉，我前阵子也编译过，遇到过这样的问题，记得是各种依赖更新就可以了。

请教下怎么更新的，我也是不熟悉

**Comment by nckf** [comment]
梯子，然后再Sync更新，多更新几次

**Comment by huoxiangdong** [comment]
> 梯子，然后再Sync更新，多更新几次

谢谢
