### ISSUE TITLE
How can I access 界面分析工具?

### ISSUE THREAD

**Issue by cccccccccccccccccnrd** [hyb1996/Auto.js#558]
Hi, how can I access the interface analysis tool from Auto.js? I can't find it in the sidebar or settings. [Screenshot](https://raw.githubusercontent.com/hyb1996/NoRootScriptDroid/master/screen-captures/ss07.png)

**Comment by nckf** [comment]
open floating window 

> 嗨，我如何从Auto.js访问界面分析工具？我在侧边栏或设置中找不到它。[屏幕截图](https://raw.githubusercontent.com/hyb1996/NoRootScriptDroid/master/screen-captures/ss07.png)

Hi @cccccccccccccccccnrd ，you can open the floating window in the sidebar

**Comment by cccccccccccccccccnrd** [comment]
Ah perfect, found it. 非常感谢你。
