### ISSUE TITLE
导不了jar啊,求解决

### ISSUE THREAD

**Issue by Liuiboy** [hyb1996/Auto.js#559]
<img width="416" alt="无标题" src="https://user-images.githubusercontent.com/46467867/71071982-8b1f3a00-21b8-11ea-8e8d-ba9e58bf8c46.png">

**Comment by nckf** [comment]
我没遇到过这个问题，不过这个涉及到 [Rhino](https://github.com/mozilla/rhino) , 建议你到上面去提 issue。

**Comment by marvel00000** [comment]
检查下jar的路径是否正确

**Comment by hyb1996** [comment]
Pro 8.5已解决
