### ISSUE TITLE
can you translate to english 

### ISSUE THREAD

**Issue by lovelyn2210** [hyb1996/Auto.js#560]
if you translate to english i will buy autojs 8 , and  invite my friend use anh buy it

**Comment by nckf** [comment]
Unfortunately, The authors have yet to announce plans, and probably won't in the near future.
Although my English is generally,But you need translation support, you can ask for it here, and I will do my best to translate for you.

**Comment by yingshaoxo** [comment]
> if you translate to english i will buy autojs 8 , and invite my friend use anh buy it

I'm working on it: https://github.com/yingshaoxo/Auto.js

**Comment by hyb1996** [comment]
We now provide the English version of the App and documentation, although this is a bit late.
[Auto.js Pro on Google Play](https://play.google.com/store/apps/details?id=org.autojs.autojspro)
[Documentation in English](https://g.pro.autojs.org/docs/#/)
