### ISSUE TITLE
库安的软件下载链接gg了，是需要自己编译了吗

### ISSUE THREAD

**Issue by Gxz-NGU** [hyb1996/Auto.js#562]

**Comment by nckf** [comment]
酷安目前官方只提供 `pro ` 版本，`4.x` 版本需要自己编译或者寻找别人编译好的前提是信任得过

**Comment by Gxz-NGU** [comment]
java程序员会maven，请问android 的编译是用gradle进行的么，是的话，我去研究研究

**Comment by nckf** [comment]
> gradle

不懂这个，我自己编译过，记得有看到过 `gradle` 命名的文件，具体的你可以自行 `clone` 项目看看。

**Comment by Gxz-NGU** [comment]
> > gradle
> 
> 不懂这个，我自己编译过，记得有看到过 `gradle` 命名的文件，具体的你可以自行 `clone` 项目看看。

ok,多谢提醒

**Comment by hyb1996** [comment]
虽然官方不再提供直接的下载链接，但是通过Git的CI系统，可以自动构建和获取没有签名的apk。
https://github.com/hyb1996/Auto.js/commit/8cab65ee1d5237b971ad9d9cc739a57326620847/checks?check_suite_id=336448810
另外，Pro版本在酷安上仍然可以下载：
https://www.coolapk.com/apk/246247

**Comment by afunx** [comment]
Auto.js Pro & Pluto.js V8
我想要写成多模块的形式，但也会遇到这个问题。可以给一个多模块可用的demo么？还是因为我是在VSCode上运行Auto.js Pro运行脚本，这种操作方式不对？我只能运行一个js文件。
