### ISSUE TITLE
获取屏幕权限，每次都须人工点击“立即开始”

### ISSUE THREAD

**Issue by ADMarcelo** [hyb1996/Auto.js#564]
每次调用requestScreenCapture()，系统都会出现“在投射/录制时显示敏感信息”提示框（没有“不再提示”那个勾选框）。需要人为手动点击一下“立即开始”,脚本才会继续执行。这样就没法完全实现定时自动化了。网上找了好久也没想到解决办法。手机是Pixel2 android 10（已启用无障碍模式，未root）。大佬，有好的解决办法么？

**Comment by ADMarcelo** [comment]
8.0 pro能解决这个问题么？

**Comment by nckf** [comment]
。。。虽然没尝试过，不过既然都有无障碍权限了为啥不用无障碍服务来解决呢？

**Comment by ADMarcelo** [comment]
> 。。。虽然没尝试过，不过既然都有无障碍权限了为啥不用无障碍服务来解决呢？

已经开启了无障碍服务，但每次请求都会弹

**Comment by hyb1996** [comment]
1. 弹框空白处可能有隐藏的不再提醒，可以尝试点一下
2. 如果没有，请用代码自动点击确定按钮

**Comment by ADMarcelo** [comment]
> 1. 弹框空白处可能有隐藏的不再提醒，可以尝试点一下
> 2. 如果没有，请用代码自动点击确定按钮

我怀疑是一旦请求就会弹出这个系统提示框，然后脚本就会运行阻塞，没法通过代码去处理。

**Comment by nckf** [comment]
> > 1. 弹框空白处可能有隐藏的不再提醒，可以尝试点一下
> > 2. 如果没有，请用代码自动点击确定按钮
> 
> 我怀疑是一旦请求就会弹出这个系统提示框，然后脚本就会运行阻塞，没法通过代码去处理。

请用线程去执行

**Comment by ADMarcelo** [comment]
> > > 1. 弹框空白处可能有隐藏的不再提醒，可以尝试点一下
> > > 2. 如果没有，请用代码自动点击确定按钮
> > 
> > 
> > 我怀疑是一旦请求就会弹出这个系统提示框，然后脚本就会运行阻塞，没法通过代码去处理。
> 
> 请用线程去执行

可以了 ，谢谢！

**Comment by Jellards** [comment]
> > > > 1. 弹框空白处可能有隐藏的不再提醒，可以尝试点一下
> > > > 2. 如果没有，请用代码自动点击确定按钮
> > > 
> > > 
> > > 我怀疑是一旦请求就会弹出这个系统提示框，然后脚本就会运行阻塞，没法通过代码去处理。
> > 
> > 
> > 请用线程去执行
> 
> 可以了 ，谢谢！

请问是怎么解决的

**Comment by ADMarcelo** [comment]
好像是加了个这个，你可以试试。很久以前的事了，记不太清楚了

**Comment by ADMarcelo** [comment]
> > > > > 1. 弹框空白处可能有隐藏的不再提醒，可以尝试点一下
> > > > > 2. 如果没有，请用代码自动点击确定按钮
> > > > 
> > > > 
> > > > 我怀疑是一旦请求就会弹出这个系统提示框，然后脚本就会运行阻塞，没法通过代码去处理。
> > > 
> > > 
> > > 请用线程去执行
> > 
> > 
> > 可以了 ，谢谢！
> 
> 请问是怎么解决的

thread.setTimeout(function(){
    toast("hello");
    click(880, 1160);
}, 5000);
加了个线程。坐标和时间的话，取决于你的手机屏幕和提示框弹出的时间。你自己适当修改一下
