### ISSUE TITLE
在VS2019中没有找到插件，那要用什么在电脑上写代码？

### ISSUE THREAD

**Issue by SickcatQAQ** [hyb1996/Auto.js#568]
![1234](https://user-images.githubusercontent.com/60089825/72708768-64309b00-3b9e-11ea-886e-8959f9e66bf5.png)

**Comment by nckf** [comment]
[VS](https://visualstudio.microsoft.com/zh-hans/vs/) ❌
[VSCode](https://code.visualstudio.com/) ✔
