### ISSUE TITLE
请问如何用js添加一个计划任务到auto.js的任务列表里面。

### ISSUE THREAD

**Issue by meetinnet** [hyb1996/Auto.js#574]
比如添加一个一小时后运行的js任务，因为我想实现每隔一小时运行一次js的目的，但是auto.js自带的按循环次数运行那个功能并不起作用，原因未知。手动设置定时任务又无法实现间隔一小时运行一次。所以想用js添加一个定时任务到列表里就可以达到效果，supermonster的蚂蚁能量脚本是可以做到的，但是那个代码太复杂新手实在看不懂。

PS：无论是用sleep还是setInterval 在js里面循环(比如5分钟)，屏幕熄灭之后device.wakeUp()无论如何也点不亮了，感觉循环就没运行起来一样，如果这时候手动点亮屏幕，那程序会接着运行，毫无异常。但不息屏的时候运行一点问题没有，百思不得。

**Comment by TonyJiangWJ** [comment]
我这里有SuperMonster003的提取版模块，你可以自己引用
- [Timers.js](https://github.com/TonyJiangWJ/Ant-Forest/blob/master/lib/Timers.js)
- 在调用的文件中这么写
  ```javascript
    let Timers = require('./Timers.js')(runtime, this)
    // 指定一小时后可以这么写
    let millis = new Date().getTime() + 3600000
    // 预定一次性的任务
    let task = Timers.addDisposableTask({
      path: mainScriptJs, // 脚本路径
      date: millis               // 指定时间戳，到达这个时间后会运行
    })
    // 定时任务预定成功后的ID task.id
  ```
- 更多调用方式可以查看Timers.js里面的代码

**Comment by meetinnet** [comment]
谢谢你的回复，现在才看到，已经过了感兴趣的阶段了，之前是想做一些别的简单工作，发现定时挺麻烦的，后来就没在搞了。非常感谢。
