### ISSUE TITLE
pro 8.0版本禁用软件的清单

### ISSUE THREAD

**Issue by li-zheng-hao** [hyb1996/Auto.js#577]
你好，在当前项目的readme中说pro版本不支持主流软件上面的模拟点击，并且在官网有详细介绍，但是我在pro版本的官网上没有看到详细的禁用软件列表，请问这些软件包括哪些？

**Comment by loveonelong** [comment]
@hyb1996 可否提供一个免责声明，在用户同意声明的情况下避开这些限制。
