### ISSUE TITLE
在安卓9.0手机里怎么用脚本

### ISSUE THREAD

**Issue by Tracker647** [hyb1996/Auto.js#578]
如题，一个499元的系统为Android9.0的野人机，装上Autojs脚本来刷快手极速版，但脚本还没启动到一半就Error：Wrapped com.stardust.autojs.runtime.exception.ScriptException: 本脚本需要此安卓版本以上才能运行:7.0，但是我手机就是7.0以上版本啊，我试了我另一台系统版本为7.0的MI Note手机倒能正常运行，那请问对于那个9.0的手机，换内核除外，怎么让脚本正常在手机正常运行？
    听说官方文档里说过有另一种编程方法不要求7.0以上版本，但是文档被墙了，希望能将相关部分截图下来谢谢

**Comment by hyb1996** [comment]
那是假的9.0吧
