### ISSUE TITLE
可以implements安卓的模块吗

### ISSUE THREAD

**Issue by tghjnjvg** [hyb1996/Auto.js#582]
可以implements安卓的模块吗

**Comment by 710850609** [comment]
可以的，比如 实现自己的webviewclient

**Comment by XeroAlpha** [comment]
严格来说，implements的对象只能是interface，WebViewClient并不是interface

**Comment by tghjnjvg** [comment]
那咋操作呢 还是不懂

**Comment by 710850609** [comment]
你去看下 这个 https://developer.mozilla.org/zh-CN/docs/Mozilla/Projects/Rhino/Scripting_Java
