### ISSUE TITLE
多个脚本同行执行，怎么控制按顺序执行，而不不是异步同时执行。

### ISSUE THREAD

**Issue by kbq670554802** [hyb1996/Auto.js#590]
多个脚本同行执行，怎么控制按顺序执行，而不不是异步同时执行。

**Comment by candivan** [comment]
这个问题要怎么处理啊？

**Comment by hyb1996** [comment]
@candivan 目前有一个思路：
1. 管理脚本中整理各个脚本的生命周期
2. 脚本和管理脚本之间用广播或者engine事件通信

计划在Pro 8.8版本加入通用的start, stop事件
