### ISSUE TITLE
安卓5模拟器，root，截图出错

### ISSUE THREAD

**Issue by dgsx61** [hyb1996/Auto.js#593]
Wrapped com.stardust.autojs.runtime.exception.ScriptException: java.lang.UnsupportedOperationException: The producer output buffer format 0x2 doesn't match the ImageReader's configured buffer format 0x1.
查了下，有些地方是可以通过设置格式来解决。但是AUTOJS这边我没看到相关的内容。不知道有没有办法解决。

**Comment by hyb1996** [comment]
Pro已修复
