### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by shijia109** [hyb1996/Auto.js#596]
项目始终跑不起来了
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'org.androidannotations:androidannotations:4.5.2', 'com.jakewharton:butterknife-compiler:9.0.0-rc2' and apply the kapt plugin: "apply plugin: 'kotlin-kapt'".

**Comment by retaw** [comment]
你应该是升级gradle还有部分它的插件版本, 然后造成的不兼容. 最简单的办法, 关掉AndroidStudio, 把工程下的所有文件用git还原. 然后重新导入工程到AndroidStudio, 提示升级各种插件的建议全部忽略, 应该就好了

**Comment by retaw** [comment]
> 项目始终跑不起来了
> app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'org.androidannotations:androidannotations:4.5.2', 'com.jakewharton:butterknife-compiler:9.0.0-rc2' and apply the kapt plugin: "apply plugin: 'kotlin-kapt'".

你应该是升级gradle还有部分它的插件版本, 然后造成的不兼容. 最简单的办法, 关掉AndroidStudio, 把工程下的所有文件用git还原. 然后重新导入工程到AndroidStudio, 提示升级各种插件的建议全部忽略, 应该就好了

**Comment by wangbo4020** [comment]
项目没有大佬维护了么，能支持下最新的 AndroidStudio 么？

**Comment by xspeed1989** [comment]
> > 项目始终跑不起来了
> > app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'org.androidannotations:androidannotations:4.5.2', 'com.jakewharton:butterknife-compiler:9.0.0-rc2' and apply the kapt plugin: "apply plugin: 'kotlin-kapt'".
> 
> 你应该是升级gradle还有部分它的插件版本, 然后造成的不兼容. 最简单的办法, 关掉AndroidStudio, 把工程下的所有文件用git还原. 然后重新导入工程到AndroidStudio, 提示升级各种插件的建议全部忽略, 应该就好了

大佬求救 错误一样 不知道怎么操作，没有安卓开发经验！
