### ISSUE TITLE
无法打包编译

### ISSUE THREAD

**Issue by JeckFS** [hyb1996/Auto.js#597]
build报错：
Could not initialize class org.jetbrains.kotlin.gradle.plugin.sources.DefaultKotlinSourceSetKt

build.gradle的第2行有问题：apply plugin: 'kotlin-android'

Gradle project sync failed. Basic functionality (e.g. editing, debugging) will not work properly.

**Comment by qq497495160** [comment]
com.android.tools.build:gradle 我使用 3.6.1对应 
gradle-wrapper.properties  distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-all.zip
