### ISSUE TITLE
Python如何运行autojs

### ISSUE THREAD

**Issue by Hello-Linux** [hyb1996/Auto.js#603]
我现在想使用python控制每个手机端上的autojs,能让其执行具体的js脚本,这个可以实现么?

**Comment by afeichuanqi** [comment]
轮训吧

**Comment by Gowa2017** [comment]
这中就是简单粗暴的了，要么你用 ADB 吧，但是这个不科学。
之前给他写过一个，用 websocket 通信的，在服务端上进行控制。
通过下发指令给 autojs 的 websocket 客户端来实现。
