### ISSUE TITLE
截图和读取颜色失败， buffer type不匹配

### ISSUE THREAD

**Issue by UWDavidWu** [hyb1996/Auto.js#604]
![QQ图片20200610091627](https://user-images.githubusercontent.com/60896832/84584248-d31dc300-adcf-11ea-8940-20ca26c27606.png)
就是运行capture screen 然后 image.pixel之后报错
在云手机上显示这个错误，请问大家有解决办法吗，谢谢.

**Comment by hyb1996** [comment]
这个在Auto.js Pro 8.1.0修复了
