### ISSUE TITLE
大神,帮看下这个问题,运行失败了,哎呀Function importClass must be called with a class

### ISSUE THREAD

**Issue by tan6458** [hyb1996/Auto.js#607]
Function importClass must be called with a class; had "[JavaPackage org.autojs.autojs.pluginclient.DevPluginService]" instead. (<init>#14)
Function importClass must be called with a class; had "[JavaPackage org.autojs.autojs.pluginclient.DevPluginService]" instead.
    at <init>:14:0
    at file:///android_asset/modules/__server__.js:2:0
    at <init>:73:0
    at <init>:66:0
    at <init>:5:0

**Comment by nckf** [comment]
代码呢
