### ISSUE TITLE
VSCode调试时，提示“设备安装的Auto.js Pro版本过低，请使用8.1.0以上版本”

### ISSUE THREAD

**Issue by Cavan2477** [hyb1996/Auto.js#610]
VSCode使用 Auto.js Pro调试时出现如下错误提示，但是点击More Info跳转到官方的网站，也没看到Auto.js Pro 8.1.0的版本。
设备安装的Auto.js Pro版本过低，请使用8.1.0以上版本

另外，在真机中也是通过酷安安装的Auto.js Pro 也没有找到8.1.0

**Comment by hyb1996** [comment]
8.1.0已发布 https://www.coolapk.com/apk/246247
