### ISSUE TITLE
页面跳转问题

### ISSUE THREAD

**Issue by zc95** [hyb1996/Auto.js#611]
请问auto.js支持页面跳转吗，比如我有一个登录页还有一个列表页，登录成功后跳转列表页，这能实现吗，没有看到相关的接口文档呢。

**Comment by hyb1996** [comment]
用engines启动另一个ui脚本即可

**Comment by zc95** [comment]
谢谢作者~用这种方式实现了功能。
然后传参我用的storage去解决的，有时候频繁跳转我怕有问题我又用engines.stopAll()去关闭所有脚本，不知道这样可行吗。

**Comment by hyb1996** [comment]
engines.start启动的时候本身就可以传参吧

**Comment by zc95** [comment]
感谢作者的回复，我只看到了engines.execScriptFile这个方法，没有看到engines.start呢。你说的本身就可以传参是用intent还是用e.getEngine().emit("say", "你好");呢，如何接受呢。

**Comment by hyb1996** [comment]
嗯，这个是一个undocumented的特性：
```
engines.execScriptFile("./main.js", {
  arguments: { a: 1}
});
```

另一个脚本：
```
let a = engines.myEngine().execArgv.a;
```

**Comment by zc95** [comment]
这个方法解决了我的问题，再次感谢作者~
