### ISSUE TITLE
请问autojs可以配合其他app开发的语言使用吗，比如我用flutter开发app的ui部分，然后执行脚本的时候用auto.js

### ISSUE THREAD

**Issue by zc95** [hyb1996/Auto.js#612]
请问autojs可以配合其他app开发的语言使用吗，比如我用flutter开发app的ui部分，然后执行脚本的时候用auto.js

**Comment by hyb1996** [comment]
你可以依赖autojs的autojs模块。flutter用message channel调用java的ScriptEngineService执行任务

**Comment by zc95** [comment]
可能因为我是做web的，对java或者安卓不是很熟悉，还是放弃这个方案吧。
目前只剩下一个下拉刷新，上拉加载更多，也就是分页的功能没有实现，其他的需求都已经用autojs的ui模块实现了，感谢作者的回复。
