### ISSUE TITLE
【BUG】用engines.stopAll()关闭所有脚本之后用engines.execScriptFile打开新的脚本之后，再进行engines.execScriptFile的操作就跳转不了页面了。

### ISSUE THREAD

**Issue by zc95** [hyb1996/Auto.js#614]
## 问题描述
我需要做一个登录页、一个列表页、一个详情页。我从列表页或者详情页退出登录之后，这个时候我的脚本应该清空之前所有的页面栈（不知道这样描述对不对，就相当于web的history），所以我用 `engines.stopAll()` 或者 `engines.all().forEach((e) => { e.forceStop() })` 去关闭了所有脚本再用engines.execScriptFile打开登录页的脚本，这个时候在登录页再用engines.execScriptFile进行跳转页面的操作就没有反应了。

经过我的尝试，不关闭所有的脚本直接跳转是不会有这样的问题的，但是这样会留下history，正常情况退出登录也是需要关闭之前的页面。

## 环境
- 机器：红米8
- 用Auto.js Alpha2打包之后就会有这样的问题，而不打包直接在autojs上跑是没有问题的

## 关键代码
```
# 关闭所有页面方式1
engines.all().forEach((e) => { e.forceStop() })

# 关闭所有页面方式2
engines.stopAll()

# 打开新的页面（脚本）
engines.execScriptFile(engines.myEngine().cwd() + url, { arguments: params })
```

**Comment by hyb1996** [comment]
建议先试下Pro版本，毕竟开源版本已经不维护了

**Comment by zc95** [comment]
嗯嗯 刚买了pro，待会试一下~
