### ISSUE TITLE
请教一下底层实现原理

### ISSUE THREAD

**Issue by Jinnrry** [hyb1996/Auto.js#619]
请问这个项目是如何通过root权限实现点击的呢？

目前根据我调研过的方案，
1、root后通过shell调用adb命令可以实现点击操作。
2、通过root权限直接写入event到/dev/input/event[xx] 

我在com/stardust/autojs/runtime/api/AbstractShell.java:79这里找到了写入相关操作，但是请问如何适配不同手机从而正确判断出触摸屏是event几呢？

**Comment by nckf** [comment]
[Shell](https://hyb1996.github.io/AutoJs-Docs/#/shell?id=shell%e5%87%bd%e6%95%b0)
请参考官方文档

**Comment by Jinnrry** [comment]
@nckf 我想问的是这个项目的实现原理，不是如何使用shell

**Comment by nckf** [comment]
···
在Auto.js大致等同于用adb执行命令"adb shell"。其实现包括两种方式：

通过java.lang.Runtime.exec执行(shell, Tap, Home等函数)
通过内嵌终端模拟器执行(RootAutomator, Shell等对象)
···

**Comment by nckf** [comment]
> @nckf 我想问的是这个项目的实现原理，不是如何使用shell

ok

**Comment by hyb1996** [comment]
https://github.com/hyb1996/Auto.js/blob/d4b731acc6e78173b535666eb28f057c46afdfca/autojs/src/main/java/com/stardust/autojs/core/inputevent/InputDevices.java

**Comment by Jinnrry** [comment]
@hyb1996 tks

**Comment by Jinnrry** [comment]
@hyb1996 感谢作者开源这么棒的项目

最近在读点击实现这块的源码，有几个问题想请教下，

1、autojs/src/main/assets/binary/root_automator  
这个文件是干嘛的呢，这个文件有源码吗？

2、com/stardust/autojs/engine/RootAutomatorEngine.java:123  
这个变量的值是通过什么方式获取到然后设置进去的呢？

3、com/stardust/autojs/core/inputevent/RootAutomator.java:67
这里的参数我看和android中getevent获取到点击操作参数一致，但是执行的命令是哪个呢？是通过sendevent执行的吗？

4、如何设置成使用root权限执行点击呢？我调试过程中始终是通过无障碍接口执行的点击，希望切换到root方式debug

**Comment by hyb1996** [comment]
1. 这个是C写的。https://github.com/hyb1996/AutoJs-RootAutomator
2和3 跑起来调试一把看看？
4. 在js里面
```javascript
let ra = new RootAutomator();
ra.xxxxxx
ra.exit();
```
