### ISSUE TITLE
小米k30手机执行text()函数获取不到文本信息

### ISSUE THREAD

**Issue by daimanman** [hyb1996/Auto.js#620]
在模拟器上执行同样的text()函数 能获取对应控件的文本信息，但是在真机上获取不到。

**Comment by hyb1996** [comment]
用desc可以么

**Comment by daimanman** [comment]
也不可以，好像是小米做了防护。我在模拟器上就能获取的到文本




| |
superbigbug
|
|
邮箱：superbigbug@163.com
|

Signature is customized by Netease Mail Master

在2020年09月14日 17:02，Stardust 写道：

用desc可以么

**Comment by myfatesky** [comment]
@daimanman 我也是这个问题，text() id() desc()啥的都无法获取信息，全部返回“”空字符串
toastLog打印控件信息，气泡通知会显示控件的信息，但是控制台中就是“”空字符串，啥都没有
我时红米note5 系统V10.3.4.0.PEICNXM，我的是17号的时候，突然就出问题了，之前都是好好的

你有没有解决这个问题啊？我觉得，可能只能降级系统解决问题了

**Comment by daimanman** [comment]
我改用模拟器了。我买这个小米k30  就是为了玩auto.js。买回来之后尽然发现用不了。好尴尬😂😂😂😂




| |
superbigbug
|
|
邮箱：superbigbug@163.com
|

Signature is customized by Netease Mail Master

在2020年09月19日 01:25，myfatesky 写道：

@daimanman 我也是这个问题，text() id() desc()啥的都无法获取信息，全部返回“”空字符串
toastLog打印控件信息，气泡通知会显示控件的信息，但是控制台中就是“”空字符串，啥都没有
我时红米note5 系统V10.3.4.0.PEICNXM，我的是17号的时候，突然就出问题了，之前都是好好的

你有没有解决这个问题啊？我觉得，可能只能降级系统解决问题了
