### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 1965514404** [hyb1996/Auto.js#624]
希望下个版本更新pro的文档到8
在pro启动时检测一次或者每多少小时后加一次检测就行了，返回桌面后一段时间，再次打开pro客户端网络不好和服务器端网络不好都会打开失败
社区能不能删去？基本无用

**Comment by hyb1996** [comment]
Pro文档在8.3已默认为在线文档
验证也会在8.3版本优化

社区嘛，暂时还不会去掉
