### ISSUE TITLE
auto能告诉我到底有啥作用吗  能看见啥效果吗 让我知道下 我在一个招聘信息啥看见的auto。js但是不知道是啥玩意

### ISSUE THREAD

**Issue by livelyPeng** [hyb1996/Auto.js#627]

**Comment by Lsx0808** [comment]
？？？？？都到这评论了 还问是啥？

**Comment by livelyPeng** [comment]
@Lsx0808 嗯 我没啥恶意啊 我是没看懂做啥的

**Comment by lovelyJason** [comment]
傻

**Comment by genspider** [comment]
什么企业需要专门的autojs技术

**Comment by wulijie** [comment]
自动化脚本啊 兄弟 就是自动帮你各种点点点  不用他这个 原生也能实现  他这个只是包了一层 可以执行js脚本

**Comment by livelyPeng** [comment]
类似于python 写脚本的那种&nbsp; 不需要人工操作？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "大熊"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 下午3:02
收件人: "hyb1996/Auto.js"<Auto.js@noreply.github.com&gt;; 
抄送: "travel96"<403802162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hyb1996/Auto.js] auto能告诉我到底有啥作用吗  能看见啥效果吗 让我知道下 我在一个招聘信息啥看见的auto。js但是不知道是啥玩意 (#627)





 
自动化脚本啊 兄弟 就是自动帮你各种点点点  不用他这个 原生也能实现  他这个只是包了一层 可以执行js脚本

**Comment by wulijie** [comment]
> 类似于python 写脚本的那种&nbsp; 不需要人工操作？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "大熊"<notifications@github.com&gt;; 发送时间: 2020年10月27日(星期二) 下午3:02 收件人: "hyb1996/Auto.js"<Auto.js@noreply.github.com&gt;; 抄送: "travel96"<403802162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [hyb1996/Auto.js] auto能告诉我到底有啥作用吗 能看见啥效果吗 让我知道下 我在一个招聘信息啥看见的auto。js但是不知道是啥玩意 (#627) 自动化脚本啊 兄弟 就是自动帮你各种点点点 不用他这个 原生也能实现 他这个只是包了一层 可以执行js脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

不需要人工操作，需要人工写js脚本，然后执行脚本自动化执行，这个框架做的不错 我研究了下  封装的可以

**Comment by hyb1996** [comment]
这就是用于写自动化小工具的软件。类似Tasker的定位。举个例子，实现充满电后播放音乐，一键达到设置深层界面等。

**Comment by livelyPeng** [comment]
那这个东西能实现在一些混合app技术上吗？比如RN，uniapp开发的APP



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Stardust"<notifications@github.com&gt;; 
发送时间: 2020年10月29日(星期四) 上午9:41
收件人: "hyb1996/Auto.js"<Auto.js@noreply.github.com&gt;; 
抄送: "travel96"<403802162@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [hyb1996/Auto.js] auto能告诉我到底有啥作用吗  能看见啥效果吗 让我知道下 我在一个招聘信息啥看见的auto。js但是不知道是啥玩意 (#627)





 
这就是用于写自动化小工具的软件。类似Tasker的定位。举个例子，实现充满电后播放音乐，一键达到设置深层界面等。

**Comment by hyb1996** [comment]
玩具/工具可以，用于生产则不能
