### ISSUE TITLE
如何定位上下两个有相同的文本按钮

### ISSUE THREAD

**Issue by xiaoyulei** [hyb1996/Auto.js#629]
一个界面上有上下多个按钮，很多按钮文本也相同，只是按钮左边有一些额外的信息。这种情况如何定位到其中一个按钮上？
我现在用textContains().findonce每次都只能找到第一个按钮，但是无法定位到下面的按钮。我的目的是想定位到第二个按钮上

**Comment by hyb1996** [comment]
xxx.find()返回一个集合，可以找到所有符合条件的控件

**Comment by xiaoyulei** [comment]
> xxx.find()返回一个集合，可以找到所有符合条件的控件

返回一个集合后，通过什么如何来区分？

**Comment by hyb1996** [comment]
如果文本之类有顺序的话（比如上下、左右），用下标就可以区分
