### ISSUE TITLE
夜神模拟器安卓7截图为纯黑

### ISSUE THREAD

**Issue by pansx** [hyb1996/Auto.js#633]
最近pro正版autojs
夜神模拟器测试版,安卓7,使用images.captureScreen()后获得的图片为纯黑色,手机上测试正常
捣鼓了各种设置都没办法,反而是安卓5的可以正常截图,但是没法点击...一new RootAutomator()就卡死...

**Comment by hyb1996** [comment]
纯黑为模拟器问题，可以看看设置里面有没有渲染之类设置，需要改成open gl

**Comment by pansx** [comment]
夜神提供的两种渲染模式我都试过,而且默认就是OpenGL+,都是黑屏,我去试了别的引擎,也是安卓5没事,安卓7黑屏...

**Comment by hyb1996** [comment]
基本上只能靠模拟自己做好兼容了

**Comment by pansx** [comment]
那能否提供一个官方推荐的安卓7模拟器?

**Comment by hyb1996** [comment]
autojs没有专门支持或者适配过模拟器

**Comment by pansx** [comment]
既然已经下结论不支持模拟器了,那没事了,买个手机去
