### ISSUE TITLE
关于监听收到短信的问题

### ISSUE THREAD

**Issue by DoGoodMore** [hyb1996/Auto.js#639]
本意是打算用监听通知的方式监听短信, 但是当我打包后发现, 有通知后不会出发监听事件执行(确认过权限已经打开过,也试过重新打开权限再运行依然拿不到), 于是我换了个思路, 以原生的代码监听数据库(短信收件箱)的变化, 但是我再注册监听者事件的时候一直在报错, 请问应该怎么创建ContentObserver的实例对象如下:
getContentResolver().registerContentObserver(Uri.parse(SMS_INBOX_URI), true, mSmsContentObserver);

**Comment by DoGoodMore** [comment]
查阅了各方文档, 尝试了各种方法都没用,

**Comment by steveRogers12** [comment]
> 查阅了各方文档, 尝试了各种方法都没用,

最近我也在写短信的功能，成功是成功了，但是遇到的是另外一个问题，
你的这个，直接可以找一下资料，建议用 onNotification 监听短信，然后 参考这个
https://blog.csdn.net/qq_30931547/article/details/106996509
就可以实现短信收发的功能了

我的问题比你的要烦躁的多，我的手机锁屏后 他就不会主动去触发脚本了，完全不知道怎么办

**Comment by DoGoodMore** [comment]
@steveRogers12  嗯， 最后也没有找到解决方案 是间隔时间后去读取数据库sms的方式实现的

**Comment by Gowa2017** [comment]
直接调用 android 内的 java 来操作吧。
