### ISSUE TITLE
captureScreen() + gravity sensor

### ISSUE THREAD

**Issue by yaldabaoth444** [hyb1996/Auto.js#641]
captureScreen() function takes wrong screenshot based on gravity sensor in Android emulator LDPlayer (https://ldplayer.net/).
requestScreenCapture has no effect. Is it possible to freeze gravity vector in custom direction?
Auto.js_4.1.1.Alpha2_461
![screencapture1605622216249](https://user-images.githubusercontent.com/25618671/99404549-940b1500-290d-11eb-9426-63f2b547a1bc.png)

**Comment by hyb1996** [comment]
Using `requestScreenCapture(true)` to lock the capturer orientation to landspace.

**Comment by yaldabaoth444** [comment]
this script made this picture
![screencapture1605955059478](https://user-images.githubusercontent.com/25618671/99875200-84424800-2c0f-11eb-8290-77b7a908612e.png)

**Comment by yaldabaoth444** [comment]
in portrait orientation same script
![screencapture1605955908375](https://user-images.githubusercontent.com/25618671/99875489-e4d28480-2c11-11eb-81ba-f53b146d0228.png)

**Comment by yaldabaoth444** [comment]
correct result, but only in portrait mode (requestScreenCapture()
![Uploading screencapture1605955946648.png…]()
)

**Comment by yaldabaoth444** [comment]
found a working option. sorry for the time taken
