### ISSUE TITLE
MainActivity_没有这个类？难道是要去掉下划线才对吗？代码中多个下划线是什么？

### ISSUE THREAD

**Issue by jimwarewj** [hyb1996/Auto.js#644]
org.autojs.autojs.ui.splash.SplashActivity
import org.autojs.autojs.ui.main.MainActivity_;

/**
 * Created by Stardust on 2017/7/7.
 */
public class SplashActivity extends BaseActivity {

![image](https://user-images.githubusercontent.com/29530485/100835400-8b3b4700-34a8-11eb-90e3-33439ac5624c.png)

**Comment by hyb1996** [comment]
aa框架生成的，build的时候自动生成
