### ISSUE TITLE
关于pro notification 无效

### ISSUE THREAD

**Issue by cnssChain** [hyb1996/Auto.js#647]
"ui";
ui.layout(
    <vertical w="*" h="*" gravity="center" >
        <button id="notify" w="auto" h="auto" text="发送通知" textSize="22sp" padding="12dp" />
        <button id="cancel" w="auto" h="auto" text="去除通知" textSize="22sp" padding="12dp" />
    </vertical>
);
ui.notify.on("click", () => {
    var manager = context.getSystemService(android.app.Service.NOTIFICATION_SERVICE);
    var notification;
    console.log(device.sdkInt);
    if (device.sdkInt >= 26) {
        var channel = new android.app.NotificationChannel("channel_id", "channel_name", android.app.NotificationManager.IMPORTANCE_DEFAULT);
        channel.enableLights(true);
        channel.setLightColor(0xff0000);
        channel.setShowBadge(false);
        manager.createNotificationChannel(channel);
        notification = new android.app.Notification.Builder(context, "channel_id")
            .setContentTitle("通知栏标题"+new Date())
            .setContentText("这是消息的内容")
            .setWhen(new Date().getTime())
            .setSmallIcon(1)
            .setTicker("这是状态栏显示的内容")
            .build();
    } else {
        notification = new android.app.Notification.Builder(context)
            .setContentTitle("通知栏标题")
            .setContentText("这是消息的内容")
            .setWhen(new Date().getTime())
            .setSmallIcon(1)
            .setTicker("这是状态栏显示的内容")
            .build();
    }
    manager.notify(1, notification);

 
});
ui.cancel.on("click", () => {
    var manager = context.getSystemService(android.app.Service.NOTIFICATION_SERVICE);
    manager.cancelAll();
    // manager.cancel(1);
});

相同的代码在普通版中可以执行 可以发送消息 但是在pro版中无反应也没有报错

**Comment by hyb1996** [comment]
setSmallIcon(1)这句，改为一个真正的icon的id

**Comment by lucian-ma** [comment]
> setSmallIcon(1)这句，改为一个真正的icon的id

pro 默认icon的id是什么啊 org.autojs.autojs.R.drawable.autojs_material 我只知道这个是普通版本的

**Comment by hyb1996** [comment]
如果是8.5.6版本，用ui.R.drawable.icon_autojs_logo; 其他用org.autojs.autojsproi.R.drawable.icon_autojs_logo
