### ISSUE TITLE
shell.setCallback方法不存在

### ISSUE THREAD

**Issue by Yaphats** [hyb1996/Auto.js#648]
var sh = new Shell(true)

sh.exec("ls /sdcard/脚本 ")
sh.setcallback({
    onOutput:function(res){
        log("output:" + res)
    },
    onNewLine:function(res){
        log("newLine:"  + res)
    }
})

TypeError:     在对象com.stardust.autojs.core.shell.Shell@625f4ab中找不到函数setcallback.

**Comment by Yaphats** [comment]
var sh = new Shell(true)

sh.exec("ls /sdcard/脚本 ")
sh.setcallback({
    onOutput:function(res){
        log("output:" + res)
    },
    onNewLine:function(res){
        log("newLine:"  + res)
    }
})





TypeError:     在对象com.stardust.autojs.core.shell.Shell@625f4ab中找不到函数setcallback.

**Comment by hyb1996** [comment]
该问题已在8.5.13以上版本修复
