### ISSUE TITLE
在线文档网页挂了

### ISSUE THREAD

**Issue by Aaronoooooo** [hyb1996/Auto.js#652]
大佬,在线文档进不去了

**Comment by pansx** [comment]
我这还能进去

**Comment by Aaronoooooo** [comment]
![image](https://user-images.githubusercontent.com/46308307/104795959-3e5bc780-57ed-11eb-89d2-13ee525575cb.png)

**Comment by Aaronoooooo** [comment]
> 我这还能进去
不是这个地址吗

**Comment by pansx** [comment]
https://hyb1996.github.io/AutoJs-Docs/#/?id=%e7%bb%bc%e8%bf%b0

**Comment by hyb1996** [comment]
这是被墙了，使用Pro版本文档https://pro.autojs.org/docs

**Comment by pansx** [comment]
被墙了不应该是连接被重置么,404很明显是服务器收到请求并返回了文档不存在啊...
