### ISSUE TITLE
构建时报错

### ISSUE THREAD

**Issue by sodarfish** [hyb1996/Auto.js#654]
开发环境： Android Studio 4.1.1
对脚本做了一些改动：
执行 File->Sync project with gradle files ,报错，猜测原因是kotlin版本问题，随后将版本改为 1.3.72  ext.kotlin_version = '1.3.72'

再次执行sync, 之前的错误没有了，多了几处关于kapt的提示，做了如下修改
增加了 apply plugin: 'kotlin-kapt'
将几处annotationProcessor 修改为了 kapt
sync通过了。

但是在构建时，多处提示类似错误，请教可能是什么原因呢？
D:\dev\autojs\Auto.js-master\app\src\main\res\layout\item_topic.xml:96: AAPT: error: attribute src (aka org.autojs.autojs:src) not found.

![image](https://user-images.githubusercontent.com/3683876/104847408-c986ab80-591a-11eb-9564-63a3a0275915.png)

**Comment by Yumore** [comment]
我在作者的基础上将部分第三方依赖更新了，仓库地址https://gitee.com/Yumore/Auto.js，但是删除了test代码和junit相关的，如果可以探讨请再次分支上查看

**Comment by Yumore** [comment]
@@请作者不要担心，我是用在App测试学习使用，并不用于其他用途，如果您介意，我会删除该仓库，感谢理解
