### ISSUE TITLE
微信获取不了布局信息

### ISSUE THREAD

**Issue by flylzj** [hyb1996/Auto.js#655]
通过悬浮窗的获取布局信息按钮无法获取微信的布局信息

**Comment by Jerome-liu-1024** [comment]
俺也一样

**Comment by hyb1996** [comment]
https://pro.autojs.org/faq

**Comment by ahkimkoo** [comment]
> https://pro.autojs.org/faq

我是pro版本，也是付费的。faq里没有类似的问题。

**Comment by ahkimkoo** [comment]
> https://pro.autojs.org/faq

我的问题解决了，是因为字体文件被墙了，翻墙就没有乱码了。不过没有搞清楚原因也没有解决办法之前就把问题close，这种简单粗暴的方式不太好吧。
