### ISSUE TITLE
loadJar Android APP 项目缓存问题

### ISSUE THREAD

**Issue by RayMMond** [hyb1996/Auto.js#672]
通过`runtime.loadJar'加载JAR成功运行一次之后，关闭APP，再次重新运行会报 
```
Wrapped com.stardust.pio.UncheckedIOException：java.io.FileNotFoundException：/data/user/0/org.autojs.autojs/cache/classes/xxxxxx.....xxxx.dex
```
在pro版本里面使用 `unloadJar` 也不行，但是清理APP所有数据（包括登录等数据）之后恢复正常，感觉与APP里面项目文件缓存有关。

PS：发现运行过一次后，在jar同级目录下会生成oat的文件夹，里面会有个 xx.jar.cur.prof 的空文件，不知道是否与此问题有关

**Comment by hyb1996** [comment]
版本？

**Comment by RayMMond** [comment]
@hyb1996  最新8.8.7
