### ISSUE TITLE
截屏后显示是黑屏

### ISSUE THREAD

**Issue by chorblack** [hyb1996/Auto.js#677]
### 问题
截屏就是个黑屏 captureScreen()
![Screenshot_20210615_230830_bin mt plus](https://user-images.githubusercontent.com/67499253/122078074-e32b1100-ce2e-11eb-8364-11770b1b2515.jpg)
设备：荣耀20 autojs版本8.8.1.0
![DD1B67F808E2C4AEE9B2441C27AE648F](https://user-images.githubusercontent.com/67499253/122078691-5b91d200-ce2f-11eb-8ff1-600c00808616.jpg)
用4.1版本的没有问题出现,但是pro不能找图找色了
这是什么原因造成的，希望能解答一下，谢谢

**Comment by chorblack** [comment]
破案了,原来得用images.captureScreen()...

**Comment by hyb1996** [comment]
这两个是等价的。估计是偶现的问题

**Comment by chorblack** [comment]
> 这两个是等价的。估计是偶现的问题

又破案了，现在又不行了，试了几十次，只有我手机有问题，虚拟机vmos都没有问题
