### ISSUE TITLE
findAllPointsForColor 在个别设备上报错 CvException

### ISSUE THREAD

**Issue by mslxl** [hyb1996/Auto.js#678]
在雷电虚拟机中可以正常运行，但是在真机(Realme GT Neo)上运行会报错

设备信息：
![Screenshot_2021-06-17-18-11-17-75_560f62a9b143ff9](https://user-images.githubusercontent.com/11132880/122377445-ac243f00-cf97-11eb-86ef-c9ea78f9e489.jpg)

错误代码片段(typescript):
```typescript
export function findColors(img: Image, firstColor: string, colors: (number | string)[][]): MatchResult | null {
  logger.i(`Detect colors(begin with ${firstColor})...`)
  let pos = images.findAllPointsForColor(img, firstColor) // 这里会报错
  logger.i(pos.length) 
  for (const p of pos) {
    if (isMatch(img, p, colors)) {
      return {
        x: p.x,
        y: p.y,
        scala: lastScala
      }
    }
  }
  return null
}
```

错误信息：
```raw
06-17 18:04:25.008 main/I: Detect colors(begin with #b8b6b8)... 
06-17 18:04:25.009 main/E: [JavaException: org.opencv.core.CvException: OpenCV(3.4.3) /build/3_4_pack-android/opencv/modules/java/generator/src/cpp/utils.cpp:38: error: (-215:Assertion failed) AndroidBitmap_lockPixels(env, bitmap, &pixels) >= 0 in function 'void Java_org_opencv_android_Utils_nBitmapToMat2(JNIEnv*, jclass, jobject, jlong, jboolean)'
] 
```

**Comment by hyb1996** [comment]
img是截图来的吗

**Comment by mslxl** [comment]
是

这是当时屏幕上的画面(2400 x 1080px):
![Screenshot_2021-06-17-18-04-41-18_246f1504a3bec15](https://user-images.githubusercontent.com/11132880/122393545-8ef76c80-cfa7-11eb-9aba-f11db06a29f5.jpg)
找的是屏幕右上的关闭按钮中心的颜色

**Comment by hyb1996** [comment]
打印一下img.bitmap的结果呢？

**Comment by mslxl** [comment]
***@***.***





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月17日(星期四) 晚上9:22
收件人: ***@***.***&gt;; 
抄送: "Dove ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hyb1996/Auto.js] findAllPointsForColor 在个别设备上报错 CvException (#678)





 
打印一下img.bitmap的结果呢？
 
&mdash;

**Comment by hyb1996** [comment]
可以先用ColorMappings的API代替。另外找图有这种情况吗

**Comment by mslxl** [comment]
找到问题了，应该是[OCR](https://pro.autojs.org/docs/?theme=dark#/zh-cn/thirdPartyPlugins?id=ocr%e6%8f%92%e4%bb%b6)对图片有副作用，将图片传入 `detect` 方法后再进行任何操作都会报错，先clone就没问题了。

抱歉添麻烦了

**Comment by hyb1996** [comment]
@HRan2004
