### ISSUE TITLE
控件属性内容获取有问题

### ISSUE THREAD

**Issue by cykaifen** [hyb1996/Auto.js#679]
某软件的控件的desc属性是三秒自动更新内容。我用autojs写了个程序一直循环去获取该控件的desc属性内容，并打印到log里。在安卓7下，每三秒更新的值全部都能正常取到。但在安卓9下，值没有全部取到。某些值控件内容已经肉眼看到被更新了，但log里打出来却一直是上次的值。请问作者这个问题是出在哪？怎么解决。目前测试安卓5和7都没问题。

**Comment by hyb1996** [comment]
试试使用以下几个方法：
1. 调用 节点.refresh()
2. 调用 auto.root.refresh()
3. 调用 auto.service.serviceInfo = auto.service.serviceInfo

这几个方法每次使用一个，依次使用看看？如果可以，务必告诉我用哪个方法成功了

**Comment by cykaifen** [comment]
感谢你的回复，这几个方法是每次循环都调用一次，还是只在程序起始调用唯一的一次。我的理解是前者，对吗？节点.fresh（）指的是对应控件.fresh（）对吗

**Comment by hyb1996** [comment]
每次循环都调用，或者检测到出问题的时候调用。是的，对应控件refresh

**Comment by cykaifen** [comment]
感谢你的回复。(1)和(3)能有效解决。请问(1)和(3)有什么区别？设置哪个更为妥当？哪个性能更佳呢？

**Comment by hyb1996** [comment]
1性能更佳，3可以理解为刷新整个无障碍服务，可以用于找不到控件的时候

**Comment by cykaifen** [comment]
非常感谢你的回答。一下就解决困扰多时的问题。差点把手机给刷成安卓7
