### ISSUE TITLE
Bitmap 被回收后 Image.isRecycled() 仍返回 false

### ISSUE THREAD

**Issue by mslxl** [hyb1996/Auto.js#682]
```javascript

function main() {
    requestScreenCapture()
    img = captureScreen()
    img.getBitmap().recycle()
    toastLog(img.isRecycled()) //false
}
main()
```
此时保存 img 会保存一张大小正确但全为黑色的图片，对图片进行任何操作会导致程序直接崩溃（无任何错误信息）

**Comment by hyb1996** [comment]
不应该单独回收image的bitmap。因为image本身包含Bitmap和一个opencv的Mat，调用img.recycle()的时候是同时回收这两个对象。

**Comment by mslxl** [comment]
了解
但是在异常操作时是不是应该让 aj 输出更多的错误信息，而不是无任何信息直接崩溃

**Comment by hyb1996** [comment]
aj会尽量试图捕捉所有错误然后输出。但是一些错误是无法捕获的，有时甚至是系统直接杀进程，这种需要看logcat日志才能知道。
