### ISSUE TITLE
Root的Press、Tap运行没有反应

### ISSUE THREAD

**Issue by ashesofdream** [hyb1996/Auto.js#683]
Pro最新版
尝试的设备、虚拟机包括：X8沙箱、VMOS虚拟机（Android7.0）、MIUI12.5（Android 11），都没效果...
代码：
var Ra = new RootAutomator();
events.on("exit",function(){Ra.exit();})
sleep(1000)
Ra.press(254,255,500) //换成tap也不行
sleep(2000)
exit()

**Comment by hyb1996** [comment]
详细版本号。”最新版“没有意义，没有人知道手里的最新版是不是最新的。

**Comment by ashesofdream** [comment]
> 详细版本号。”最新版“没有意义，没有人知道手里的最新版是不是最新的。

Pro 8.8.5-0

**Comment by hyb1996** [comment]
最新是8.8.12，更新即可
