### ISSUE TITLE
想请问一下，JS运行正常，打包成APK就闪退，是什么原因？

### ISSUE THREAD

**Issue by tm123666** [hyb1996/Auto.js#687]
想请问一下，JS运行正常，打包成APK就闪退，是什么原因？

**Comment by hyb1996** [comment]
请提供以下信息：
版本号，logcat日志

**Comment by tm123666** [comment]
你好，版本是 V4.1.0 ，刚刚尝试复现，却发现打包后，打开不闪退了。
但是出现了一个新问题，无障碍明明打开着，但是一打开应用，又会跳转到无障碍页面去。

**Comment by hyb1996** [comment]
4.1.0不再维护，目前只接收8.0最新版本的问题反馈
