### ISSUE TITLE
运行报错：ReferenceError: "runtime" is not defined.

### ISSUE THREAD

**Issue by Fire-Star** [hyb1996/Auto.js#688]
![image](https://user-images.githubusercontent.com/17548618/125271542-77f53180-e33d-11eb-80a3-1432c498ca08.png)

**Comment by Fire-Star** [comment]
红米note3

**Comment by hyb1996** [comment]
升级到最新版本，比如8.8.15以上

**Comment by Fire-Star** [comment]
我使用的版本是8.8.5-0呢，就是最新版本了。

**Comment by hyb1996** [comment]
最新版是8.8.15，不是8.8.5，这里下载 https://pro.autojs.org

**Comment by hyb1996** [comment]
由于没有回复，关闭此issue，若仍然有问题可重新打开

**Comment by KimChow** [comment]
if (className("android.view.View").text("").exists() ) {
 ....
}

我在使用这样的办法去判断，因为界面上没有那个文字，会存在报错。导致脚本无法运行
