### ISSUE TITLE
http失败会疯狂重试

### ISSUE THREAD

**Issue by chenyu1990** [hyb1996/Auto.js#702]
成功请求只请求一次
statusCode != 200     不设置http.__okhttp__.setTimeout 会重试请求4次
statusCode != 200     设置http.__okhttp__.setTimeout(10000) 会重试请求10几次

**Comment by hyb1996** [comment]
http.__okhttp__.setMaxRetries(0);

**Comment by chenyu1990** [comment]
感谢大佬
