### ISSUE TITLE
雷电模拟器用不了 pro 9

### ISSUE THREAD

**Issue by mingcong1103** [hyb1996/Auto.js#738]
雷电模拟器用不了 pro 9
官方下载最新版 直接安装不了 
解析安装包失败

**Comment by mingcong1103** [comment]
32位 和 64位 都测试了

**Comment by hyb1996** [comment]
需要雷电模拟器4，另外需要关闭XP框架或者隐藏XP（因360加固导致）。若还有问题，可以重新打开issue。
