### ISSUE TITLE
autojs 确定支持esmodule 模式么？

### ISSUE THREAD

**Issue by helloinfinitech** [hyb1996/Auto.js#744]
pro9 中 使用 vscode 插件创建的工程，启用esmodule后，import的所有模块都提示无法找到相应的package，而import 非autojs的其他模块却没问题。改成commonjs 使用require 导入也却没问题。是autojs 不支持esmodule么？

**Comment by yupplt** [comment]
确定

**Comment by helloinfinitech** [comment]
需要使用内测版本。
