### ISSUE TITLE
关于 accessibility 的建议

### ISSUE THREAD

**Issue by MyZafkiel** [hyb1996/Auto.js#745]
关于无障碍的建议先贴一份示例代码

`select({ text: "test" })
  .first()
  .then((res) => {
    res.click();
  })
  .catch((e) => {
    console.log(e);
  });
`
在现在代码执行上不管找没找到都是往.then走我觉得这样是不合理的,如果没找到应该往.catch上走这样才是比较合理的 纯属个人建议,作者要是不喜欢,当我没说

**Comment by hyb1996** [comment]
我会加个firstOrNull()为可空的，默认first()为抛异常实现

**Comment by hyb1996** [comment]
9.3版本已公测，这里的API已调整
