### ISSUE TITLE
为什么不支持js class语法

### ISSUE THREAD

**Issue by 1234xxcc** [hyb1996/Auto.js#748]

**Comment by 1234xxcc** [comment]
class Auto extends Auto.js {}

**Comment by hyb1996** [comment]
9.0版本是支持的（使用Node.js模式编写）

**Comment by 1234xxcc** [comment]
> 9.0版本是支持的（使用Node.js模式编写）

哪里可以看老版本都支持什么语法，新版本支持什么语法

**Comment by 1234xxcc** [comment]
也不支持 new Promise().then().catch()

**Comment by hyb1996** [comment]
目前autojspro有两个引擎，旧版rhino支持特性https://mozilla.github.io/rhino/compat/engines.html（版本1.7.14）新版nodejs引擎基本上跟随最新的es标准（目前为nodejs 16)
