### ISSUE TITLE
请教 macbook 上修改内容 运行 保存到设备 均非最新代码

### ISSUE THREAD

**Issue by 1605412705** [hyb1996/Auto.js#752]
大佬好, 请教个问题,  本地修改文件 运行, 保存到设备 代码不更新 都是之前的版本, 删除也无效
MacBook  12,.5
Vscode 1.71.2

QQ频道不存在, 扫了眼文档 搜索引擎没有找到对应的说明,  

## 直接运行

```
09-20 15:49:55.001 Script-39 Main [/data/data/org.autojs.autojspro/cache/remote_project/a664c274463507787519416f40b70aeb/main.js]/V: 开始运行[/data/data/org.autojs.autojspro/cache/remote_project/a664c274463507787519416f40b70aeb/main.js] 
09-20 15:49:55.211 Thread-99/D: {
  node: '16.14.0',
  v8: '9.4.146.24-node.20',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  autojspro: 'Pro 9.2.13-0',
  openssl: '1.1.1m+quic',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
} 
09-20 15:49:55.214 Thread-99/D: process exit: 0 
09-20 15:49:55.214 Script-39 Main [/data/data/org.autojs.autojspro/cache/remote_project/a664c274463507787519416f40b70aeb/main.js]/V: 
------------
[/data/data/org.autojs.autojspro/cache/remote_project/a664c274463507787519416f40b70aeb/main.js]运行结束，用时0.211000秒

```

**Comment by hyb1996** [comment]
插件正在重构，加入内测群753767852体验

**Comment by 1605412705** [comment]
> 

加入qq群需要回答问题,  认知的答案是错误的, 我已购买的会员, 请问这个答案在哪里可以看到

**Comment by hyb1996** [comment]
@1605412705 已更新问题，再试试

**Comment by 1605412705** [comment]
> @1605412705 已更新问题，再试试

您好, 我重新下载了Auto.js Pro  版本为Pro 9.2.13-0, 重新安装了vscode插件 1.4.1,  保存到手机还是运行还是走的cache

1. 新建v8项目, 保存到设备, 运行 toastLog 显示  Hello, Auto.js Pro 9.2.13-0 
2. 修改main.js toastLog 内容为11111 运行 toastLog 显示  Hello, Auto.js Pro 9.2.13-0 , 设备上的代码还是 之前的
3. 保存到设备 , 设备上的代码还是  Hello, Auto.js Pro 9.2.13-0 不是保存上去的内容
4. 删除设备上的项目, 重新保存, 内容还是第一次的内容.....  

我不确定是不是我的问题,还是电脑系统的问题, 有人碰到我这种问题吗
MacBook  12,.5
Vscode     1.71.2
小米MIUI: 13.0.11  
Android:   12

**Comment by hyb1996** [comment]
@1605412705 需要内测9.3版本，但是内测版还不太完善，你可以试试

**Comment by 1605412705** [comment]
@hyb1996  我比较小白哈 我删掉package.json 就能正常调试了, 我先来回折腾的用着吧, 那个QQ群的答案 npm 错误 加不了, 这个应该是购买用户才能加把, 这个答案我在哪里可以获取到哈(我已购买了会员, 账号是zixiaxxxxx@gmail.com 那个).需要我单独发邮件获取答案不

**Comment by 1605412705** [comment]
require 模块 提示 ReferenceError: "module" is not defined.

**Comment by 1605412705** [comment]
还有 博客文档里图片 404了

**Comment by hyb1996** [comment]
> require 模块 提示 ReferenceError: "module" is not defined.

rhino的模块系统不完善，不能直接运行module，module只能被require。nodejs引擎则没有这个问题

**Comment by 1605412705** [comment]
还是没有解决, mac下 保存到设备  保存的内容还是第一次上传的内容

**Comment by hyb1996** [comment]
> 还是没有解决, mac下 保存到设备 保存的内容还是第一次上传的内容

@1605412705 使用的是9.3.4版本和9.0.5 VSCode插件？
