### ISSUE TITLE
Error: EMFILE: too many open files 

### ISSUE THREAD

**Issue by catpigdog** [hyb1996/Auto.js#753]
项目加入了git版本控制后，.git文件夹内容数量太大 在mac上【保存项目到设备】或【运行项目】指令会报错  ERR EMFILE: too many open files
Auto.js-Pro-Ext插件可以排除.git文件夹的内容吗？

**Comment by hyb1996** [comment]
目前版本插件可以找project.json加上ignore: [".git"]忽略，另外建议加入内测569938976，内测版极大优化了插件体验。

**Comment by hyb1996** [comment]
该版本已公测，参考https://blog.autojs.org/2022/10/15/vscode-debug-v9/
