### ISSUE TITLE
waitForPackage，currentPackage() 有bug?

### ISSUE THREAD

**Issue by caiabc** [hyb1996/Auto.js#756]
你好，前几天使用您的最新版本autojs pro，脚本运行老是卡住。
后来，经过调试，发现了是有两个函数，无法正确执行导致的，估计是bug了，所以，来反映一下。

waitForPackage无法获得当前正确的app包名，导致卡住。就是在非autojs界面上，无法获得对应新启动的app的名称。
currentPackage()也无法获得当前正确的app包名，导致我无法通过判断currentPackage()获得变通规避waitForPackage问题的方法。

奇怪的是，currentPackage()无法获得正确的app名称的同时，currentActivity()是能够获得正确的结果的。
麻烦验证一下，如果确实有问题，修复一下。
不管什么结果，麻烦回个帖。

谢谢！

**Comment by hyb1996** [comment]
已在邮件中回复，根据有关规定，涉政应用不能被操作。
