### ISSUE TITLE
auto.js pro9 api第二版 nodejs 引擎, 如何使用setAdpater

### ISSUE THREAD

**Issue by MichaelLin0713** [hyb1996/Auto.js#776]
原本rhino引擎時, 
var w = floaty.window(
<spinner id="TestSpinner"...
);
w.TestSpinner.setAdapter(...);
這樣可以接到自定義的接口

但是nodejs引擎時,
var window = createWindow();
window.setViewFromXml(`
<spinner id="TestSpinner"...
);
已經無法再使用windows.TestSpinner
可以使用
var ID_TestSpinner  = window.view.findView("TestSpinner"); 
但是這樣是取得JSView不是View.
ID_TestSpinner.setAdapter是無法接上，但也不支援ClassName用ID取得.
要怎麼轉到XML, ID上的接口?

**Comment by hyb1996** [comment]
在9.3以上版本的内置示例中有相关例子，Node.js -> Node.js中使用UI -> 使用Android原生界面 -> main.js

**Comment by MichaelLin0713** [comment]
> 在9.3以上版本的内置示例中有相关例子，Node.js -> Node.js中使用UI -> 使用Android原生界面 -> main.js

所以目前Nodejs引擎，在floating_window下 還是未支援自定義UI接口所以rhino下的setAdapter, 無法在nodejs下的floating_window使用?

**Comment by hyb1996** [comment]
不管是在悬浮窗还是普通界面，都可以使用setAdapter，参照上面给出的例子。
