### ISSUE TITLE
NodeJS下的globalconsole

### ISSUE THREAD

**Issue by MichaelLin0713** [hyb1996/Auto.js#778]
是否rhino下的懸浮視窗，使用console.show(); 會出現console界面

1. 但在Nodejs下，是否一定要放到XML裡，使用<globalconsole id="console" w=?? h=?? />
但是findView("console")後, 怎麼像console.log("...")，把字串放在上面
一樣有支援info/warn/error嗎?

2. 為什麼我執行範例裡的Node.js>Nodejs中使用UI>懸浮窗>懸浮日誌.node.js
   左上角會秀一堆紅色error字串，然後才會出現vscode裡執行結果的白色字串

   當我自己寫一個floating window nodejs script, 將globalconsole放在XML秀出來後一樣會先秀一堆error字串(但是vscode上看不到)接下來會秀vscode裡面執行的白色字串

**Comment by hyb1996** [comment]
1. 一样使用console.log, console.info等函数
2. error内容可能是读取标准输出的内容，是其他代码（比如链接器、一些第三方库）打印的，在以后改进node的控制台方案后，这些错误会消失，目前忽略即可

**Comment by MichaelLin0713** [comment]
> 1. 一样使用console.log, console.info等函数
> 
我的floating window nodejs script, globalconsole放在XML秀出來後, 
使用console.clear() 無法清除node控制台上的訊息.
使用console.log("...") 無法打印出訊息.

請問還有什麼該注意的地方

**Comment by MichaelLin0713** [comment]
我一次測試出現globalconsole後
console.clear(), console.log, console.info, console.warn, console.error 五個函式後
console.clear(), console.log, console.info 無作用
console.warn和console.error都會打出紅色的字

雖然終於可以在Nodejs下的floating windows下使用console, 但整個畫面都紅色的字，還會多出"/E:"的字樣，怎麼看就是很奇怪.
console.clear() 無法使用下，是會秀出之前vscode之前編譯的訊息(雖然上面有說可以忽略) 但好希望下一版趕快發出來.

**Comment by hyb1996** [comment]
console.clear()本身是nodejs的函数，无法用于清空控制台。暂时请勿调用此函数，后续可能重写此函数。
