### ISSUE TITLE
autojs://sdk/v1.js  在ifarme无效 获取不到值

### ISSUE THREAD

**Issue by xsw1006931693** [hyb1996/Auto.js#779]

**Comment by xsw1006931693** [comment]
大神 麻烦看看这个问题啊，在ifarme里面能读取到v1。js 但是使用就不能用

**Comment by hyb1996** [comment]
有什么报错信息吗

**Comment by xsw1006931693** [comment]
不报错，webview引用 html1 ，html1的ifarme 引用html2，在html2 里面调用$autojs.invoke，后台可以正常执行，但是返回值一直在前台接受不到，当然有await哈，

**Comment by hyb1996** [comment]
这里回调给js时是直接用webview.evaluateJavaScript，如果iframe的域名不同，则无法共享彼此的全局变量和函数。

**Comment by xsw1006931693** [comment]
哦 这样啊。明白了。
（1）那可不可以使用 localstorage 作为中转完成数据传输呢？
（2） 请问咱们的storage ，localstorage他俩是一个东西么，
（3）后台的js如何调用localstorage

**Comment by hyb1996** [comment]
(1) 不清楚，建议搜索相关资料
(2) 不是
(3) 在autojs环境无法直接调用web环境的localstorage，需要通过通信/evaluateJavaScript去完成

**Comment by xsw1006931693** [comment]
那请问 storage是使用indexedDB 实现的么，我看js也可以直接访问 indexedDB 和sqlite数据库，我想最好可以直接和咱们的storage 打通就直接取值了

**Comment by xsw1006931693** [comment]
我知道如何通信 谢谢大神了
